/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.*;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import net.miginfocom.swing.*;

/**
 *
 * @author Thomas Zimmermann
 */
public class _DlgRezensionErzeugen extends javax.swing.JDialog {

    /**
     * Creates new form _DlgRezensionErzeugen
     *
     * @param parent
     * @param modal
     */
    public _DlgRezensionErzeugen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        conn = null;

        // Datenbank-Treiber laden
        try {
            Class.forName(Modulhelferlein.dbDriver);
        } catch (ClassNotFoundException exept) {
            Modulhelferlein.Fehlermeldung("ClassNotFoundException: Treiber nicht gefunden. " + exept.getMessage());
        }

        // Verbindung zur Datenbank über die JDBC-Brücke
        try {
            conn = DriverManager.getConnection(Modulhelferlein.dbUrl, Modulhelferlein.dbUser, Modulhelferlein.dbPassword);
        } catch (SQLException exept) {
            Modulhelferlein.Fehlermeldung("SQL-Exception: Verbindung zur Datenbank nicht moeglich. " + exept.getMessage());
        }

        try {
            SQLAnfrage = null;    // Anfrage erzeugen
            SQLAnfrage = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            result = SQLAnfrage.executeQuery("SELECT * FROM tbl_adresse WHERE ADRESSEN_Typ = 'Rezensent'");

            while (result.next()) {
                eintrag = Integer.toString(result.getInt("ADRESSEN_ID")) + ", " + result.getString("ADRESSEN_Name")
                        + ", " + result.getString("ADRESSEN_Vorname");
                listModel.addElement(eintrag);

            }    // while

        } catch (SQLException exept) {
            Modulhelferlein.Fehlermeldung("SQL-Exception: Verbindung zur Datenbank nicht moeglich. " + exept.getMessage());
        }        // try

        initComponents();

        Anlass.add(Anfrage);
        Anlass.add(Wunsch);
        Anlass.add(Initiative);

        Format.add(rbPDF);
        Format.add(rbDOC);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel1 = new JLabel();
        label1 = new JLabel();
        jLabel3 = new JLabel();
        Anfrage = new JRadioButton();
        field_Datum = new JTextField();
        rbPDF = new JRadioButton();
        Wunsch = new JRadioButton();
        rbDOC = new JRadioButton();
        Initiative = new JRadioButton();
        jLabel2 = new JLabel();
        scrollPane = new JScrollPane();
        Rezensenten = new JList<>();
        Erstellen = new JButton();
        Schliessen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles Verlag");
        setResizable(false);
        setFont(new Font(Font.DIALOG, Font.BOLD, 12));
        var contentPane = getContentPane();

        //======== panel1 ========
        {
            panel1.setLayout(new MigLayout(
                "insets 0,hidemode 3,gap 5 5",
                // columns
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]",
                // rows
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[]" +
                "[]" +
                "[]" +
                "[]"));

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel1.setText("Rezensionen erzeugen");
            panel1.add(jLabel1, "cell 0 0 2 1");

            //---- label1 ----
            label1.setText("auf ...");
            label1.setFont(label1.getFont().deriveFont(label1.getFont().getStyle() | Font.BOLD, label1.getFont().getSize() + 1f));
            panel1.add(label1, "cell 0 2");

            //---- jLabel3 ----
            jLabel3.setText("Ausgabeformat");
            jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | Font.BOLD));
            panel1.add(jLabel3, "cell 5 2");

            //---- Anfrage ----
            Anfrage.setSelected(true);
            Anfrage.setText("... Grund Nachfrage vom ");
            panel1.add(Anfrage, "cell 0 3 2 1");

            //---- field_Datum ----
            field_Datum.setMinimumSize(new Dimension(6, 25));
            field_Datum.setPreferredSize(new Dimension(100, 25));
            panel1.add(field_Datum, "cell 2 3");

            //---- rbPDF ----
            rbPDF.setSelected(true);
            rbPDF.setText("PDF");
            panel1.add(rbPDF, "cell 5 3");

            //---- Wunsch ----
            Wunsch.setText("... Wunsch des Autors");
            panel1.add(Wunsch, "cell 0 4 2 1");

            //---- rbDOC ----
            rbDOC.setText("DOC");
            rbDOC.setEnabled(false);
            panel1.add(rbDOC, "cell 5 4");

            //---- Initiative ----
            Initiative.setText("... Grund Eigeninitiative");
            panel1.add(Initiative, "cell 0 5 2 1");

            //---- jLabel2 ----
            jLabel2.setText("Liste der Rezensenten");
            jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | Font.BOLD));
            panel1.add(jLabel2, "cell 0 7 2 1");

            //======== scrollPane ========
            {

                //---- Rezensenten ----
                Rezensenten.setModel(listModel);
                scrollPane.setViewportView(Rezensenten);
            }
            panel1.add(scrollPane, "cell 0 8 3 1");

            //---- Erstellen ----
            Erstellen.setText("Erstellen");
            Erstellen.addActionListener(e -> ErstellenActionPerformed(e));
            panel1.add(Erstellen, "cell 4 10");

            //---- Schliessen ----
            Schliessen.setText("Schlie\u00dfen");
            Schliessen.addActionListener(e -> SchliessenActionPerformed(e));
            panel1.add(Schliessen, "cell 5 10");
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, 453, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE))
        );
        setSize(460, 430);
        setLocationRelativeTo(getOwner());

        //---- buttonGroup1 ----
        var buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(Anfrage);
        buttonGroup1.add(Wunsch);
        buttonGroup1.add(Initiative);
    }// </editor-fold>//GEN-END:initComponents

    private void ErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErstellenActionPerformed
        // TODO add your handling code here:
        Integer Auswahl = 0;

        if (JOptionPane.showConfirmDialog(null, "Sollen die Briefe wirklich erstellt werden?", "Bestätigung",
                JOptionPane.YES_NO_OPTION) == 0) {

            // liste der markierten Einträge holen
            // int auswahlliste[] = Rezensenten.getSelectedIndices();
            List<String> auswahlliste = Rezensenten.getSelectedValuesList();

            // geht die Liste durch
            // geht die Liste durch
            for (int i = 0, n = auswahlliste.size(); i < n; i++) {

                // for (int i = 0, n = auswahlliste.length; i < n; i++) {
                String strAuswahl = auswahlliste.get(i);
//helferlein.Infomeldung(strAuswahl);
                // String strAuswahl = (String)Rezensenten.getModel().getElementAt(auswahlliste[i]);
                String[] splitRezensent = strAuswahl.split(", ");
//helferlein.Infomeldung(splitRezensent[0]);

                // ruft jeweils die Adressen des Rezensenten ab
                try {
                    result = SQLAnfrage.executeQuery("SELECT * FROM tbl_adresse WHERE ADRESSEN_ID = "
                            + splitRezensent[0]);
                    result.next();

                    // und ruft briefRezension auf
                    try {
                        if (Anfrage.isSelected()) {
                            Auswahl = 0;
                        } else {
                            if (Wunsch.isSelected()) {
                                Auswahl = 1;
                            } else {
                                Auswahl = 2;
                            }
                        }
//helferlein.Infomeldung(Autor); 
                        if (rbPDF.isSelected()) {
                            briefRezension.briefPDF(Auswahl,
                                    field_Datum.getText(),
                                    Anrede,
                                    Autor,
                                    Titel,
                                    Beschreibung,
                                    ISBN,
                                    result.getString("ADRESSEN_NAME"),
                                    result.getString("ADRESSEN_ZEITSCHRIFT"),
                                    result.getString("ADRESSEN_ZUSATZ_1"),
                                    result.getString("ADRESSEN_ZUSATZ_2"),
                                    result.getString("ADRESSEN_NAMENSZUSATZ"),
                                    result.getString("ADRESSEN_VORNAME"),
                                    result.getString("ADRESSEN_NAME"),
                                    result.getString("ADRESSEN_STRASSE"),
                                    result.getString("ADRESSEN_PLZ") + " " + result.getString("ADRESSEN_ORT"),
                                    result.getString("ADRESSEN_ANREDE"),
                                    Preis,
                                    Seiten);

                            briefRechnungMahnung.briefPDF(Modulhelferlein.makeBestellung(result.getString("ADRESSEN_ZEITSCHRIFT"),
                                    result.getString("ADRESSEN_ZUSATZ_1"),
                                    result.getString("ADRESSEN_ZUSATZ_2"),
                                    result.getString("ADRESSEN_NAMENSZUSATZ")
                                    + result.getString("ADRESSEN_VORNAME")
                                    + result.getString("ADRESSEN_NAME"),
                                    result.getString("ADRESSEN_STRASSE"),
                                    result.getString("ADRESSEN_PLZ") + " " + result.getString("ADRESSEN_ORT"),
                                    GBuch,
                                    GTyp,
                                    GAnzahl),
                                    1,
                                    "",
                                    0);
                        } else {
                            briefRezension.briefDOC(Auswahl,
                                    field_Datum.getText(),
                                    Anrede,
                                    Autor,
                                    Titel,
                                    Beschreibung,
                                    ISBN,
                                    result.getString("ADRESSEN_NAME"),
                                    result.getString("ADRESSEN_ZEITSCHRIFT"),
                                    result.getString("ADRESSEN_ZUSATZ_1"),
                                    result.getString("ADRESSEN_ZUSATZ_2"),
                                    result.getString("ADRESSEN_NAMENSZUSATZ"),
                                    result.getString("ADRESSEN_VORNAME"),
                                    result.getString("ADRESSEN_NAME"),
                                    result.getString("ADRESSEN_STRASSE"),
                                    result.getString("ADRESSEN_PLZ") + " " + result.getString("ADRESSEN_ORT"),
                                    result.getString("ADRESSEN_ANREDE"),
                                    Preis,
                                    Seiten);

                            briefRechnungMahnung.briefDOC(Modulhelferlein.makeBestellung(result.getString("ADRESSEN_ZEITSCHRIFT"),
                                    result.getString("ADRESSEN_ZUSATZ_1"),
                                    result.getString("ADRESSEN_ZUSATZ_2"),
                                    result.getString("ADRESSEN_NAMENSZUSATZ") + " "
                                    + result.getString("ADRESSEN_VORNAME") + " "
                                    + result.getString("ADRESSEN_NAME"),
                                    result.getString("ADRESSEN_STRASSE"),
                                    result.getString("ADRESSEN_PLZ") + " " + result.getString("ADRESSEN_ORT"),
                                    GBuch,
                                    GTyp,
                                    GAnzahl),
                                    1,
                                    "");
                        }
                    } catch (Exception e) {
                        Modulhelferlein.Fehlermeldung("Exception: " + e.getMessage());
                    }    // try
                } catch (SQLException e1) {
                    Modulhelferlein.Fehlermeldung("SQL-Exception: " + e1.getMessage());
                }        // schickt SQL an DB und erzeugt ergebnis -> wird in result gespeichert
            } // for
        } // if
        this.dispose();
    }//GEN-LAST:event_ErstellenActionPerformed

    private void SchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchliessenActionPerformed
        // TODO add your handling code here:
        try {
            SQLAnfrage.close();
            conn.close();
        } catch (SQLException exept) {
            Modulhelferlein.Fehlermeldung("SQL-Exception: " + exept.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_SchliessenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        Anrede = args[0];
        Autor = args[1];
        Titel = args[2];
        Beschreibung = args[3];
        ISBN = args[4];
        Preis = args[5];
        Seiten = args[6];
        GBuch = Integer.parseInt(args[7]);
        GTyp = Integer.parseInt(args[8]);
        GAnzahl = Integer.parseInt(args[9]);

        /**
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
         * } catch (ClassNotFoundException | InstantiationException |
         * IllegalAccessException | javax.swing.UnsupportedLookAndFeelException
         * ex) {
         * java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); }
         */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgRezensionErzeugen dialog = new _DlgRezensionErzeugen(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel1;
    private JLabel label1;
    private JLabel jLabel3;
    private JRadioButton Anfrage;
    private JTextField field_Datum;
    private JRadioButton rbPDF;
    private JRadioButton Wunsch;
    private JRadioButton rbDOC;
    private JRadioButton Initiative;
    private JLabel jLabel2;
    private JScrollPane scrollPane;
    private JList<String> Rezensenten;
    private JButton Erstellen;
    private JButton Schliessen;
    // End of variables declaration//GEN-END:variables

    private Connection conn;
    private Statement SQLAnfrage;
    private ResultSet result;
    private String SQL;
    private String eintrag;
    private DefaultListModel<String> listModel = new DefaultListModel<>();

    private static String Autor;
    private static String Anrede;
    private static String Titel;
    private static String Beschreibung;
    private static String ISBN;
    private static String Preis;
    private static String Seiten;
    private static Integer GBuch;
    private static Integer GTyp;
    private static Integer GAnzahl;

    private ButtonGroup Format = new ButtonGroup();
    private ButtonGroup Anlass = new ButtonGroup();
}
