/*
 * Copyright (C) 2018 EDV-Beratung Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package milesVerlagMain;

import java.awt.*;
import java.awt.Color;
import java.io.IOException;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.border.*;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import static org.apache.pdfbox.pdmodel.common.PDRectangle.A4;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import static milesVerlagMain.ModulHelferlein.AusgabeLB;
import static milesVerlagMain.ModulHelferlein.Ausgabe;
/**
 *
 * @author thoma
 */
public class _DlgAdresseDrucken extends javax.swing.JDialog {

    /**
     * Creates new form _DlgAdresseDrucken
     * @param parent
     * @param modal
     */
    public _DlgAdresseDrucken(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton2);
        buttonGroup.add(jRadioButton3);
        buttonGroup.add(jRadioButton4);
        buttonGroup.add(jRadioButton5);
        buttonGroup.add(jRadioButton6);
        buttonGroup.add(jRadioButton7);
        buttonGroup.add(jRadioButton8);
        buttonGroup.add(jRadioButton9);
        buttonGroup.add(jRadioButton10);
        buttonGroup.add(jRadioButton11);
        buttonGroup.add(jRadioButton12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel1 = new JLabel();
        jButtonDrucken = new JButton();
        jButtonAbbrechen = new JButton();
        jRadioButton11 = new JRadioButton();
        jRadioButton1 = new JRadioButton();
        jRadioButton12 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jRadioButton3 = new JRadioButton();
        jRadioButton4 = new JRadioButton();
        jRadioButton5 = new JRadioButton();
        jRadioButton6 = new JRadioButton();
        jRadioButton7 = new JRadioButton();
        jRadioButton8 = new JRadioButton();
        jRadioButton9 = new JRadioButton();
        jRadioButton10 = new JRadioButton();
        jLabel2 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles-Verlag");
        setResizable(false);
        Container contentPane = getContentPane();

        //======== panel1 ========
        {

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel1.setText("Adressetikett drucken");

            //---- jButtonDrucken ----
            jButtonDrucken.setText("Drucken");
            jButtonDrucken.addActionListener(e -> jButtonDruckenActionPerformed(e));

            //---- jButtonAbbrechen ----
            jButtonAbbrechen.setText("Abbrechen");
            jButtonAbbrechen.addActionListener(e -> jButtonAbbrechenActionPerformed(e));

            //---- jRadioButton11 ----
            jRadioButton11.setBackground(new Color(255, 255, 204));
            jRadioButton11.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton11.setText(" 11");
            jRadioButton11.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton1 ----
            jRadioButton1.setBackground(new Color(255, 255, 204));
            jRadioButton1.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton1.setText(" 01");
            jRadioButton1.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton12 ----
            jRadioButton12.setBackground(new Color(255, 255, 204));
            jRadioButton12.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton12.setText(" 12");
            jRadioButton12.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton2 ----
            jRadioButton2.setBackground(new Color(255, 255, 204));
            jRadioButton2.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton2.setText(" 02");
            jRadioButton2.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton3 ----
            jRadioButton3.setBackground(new Color(255, 255, 204));
            jRadioButton3.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton3.setText(" 03");
            jRadioButton3.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton4 ----
            jRadioButton4.setBackground(new Color(255, 255, 204));
            jRadioButton4.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton4.setText(" 04");
            jRadioButton4.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton5 ----
            jRadioButton5.setBackground(new Color(255, 255, 204));
            jRadioButton5.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton5.setText(" 05");
            jRadioButton5.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton6 ----
            jRadioButton6.setBackground(new Color(255, 255, 204));
            jRadioButton6.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton6.setText(" 06");
            jRadioButton6.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton7 ----
            jRadioButton7.setBackground(new Color(255, 255, 204));
            jRadioButton7.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton7.setText(" 07");
            jRadioButton7.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton8 ----
            jRadioButton8.setBackground(new Color(255, 255, 204));
            jRadioButton8.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton8.setText(" 08");
            jRadioButton8.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton9 ----
            jRadioButton9.setBackground(new Color(255, 255, 204));
            jRadioButton9.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton9.setText(" 09");
            jRadioButton9.setBorder(LineBorder.createBlackLineBorder());

            //---- jRadioButton10 ----
            jRadioButton10.setBackground(new Color(255, 255, 204));
            jRadioButton10.setFont(new Font("Courier New", Font.BOLD, 14));
            jRadioButton10.setText(" 10");
            jRadioButton10.setBorder(LineBorder.createBlackLineBorder());

            //---- jLabel2 ----
            jLabel2.setText("Avery Zweckform 4781");

            GroupLayout panel1Layout = new GroupLayout(panel1);
            panel1.setLayout(panel1Layout);
            panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup()
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jRadioButton2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton3, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jRadioButton4, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton5, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jRadioButton6, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton7, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jRadioButton8, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton9, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jRadioButton10, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton11, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jRadioButton12, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jButtonDrucken)
                                .addGap(9, 9, 9)
                                .addComponent(jButtonAbbrechen)))
                        .addContainerGap(53, Short.MAX_VALUE))
            );
            panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(11, 11, 11)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(11, 11, 11)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6))
                        .addGap(11, 11, 11)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8))
                        .addGap(11, 11, 11)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10))
                        .addGap(11, 11, 11)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton12))
                        .addGap(41, 41, 41)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jButtonDrucken)
                            .addComponent(jButtonAbbrechen))
                        .addContainerGap(20, Short.MAX_VALUE))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(getOwner());

        //---- buttonGroup ----
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(jRadioButton11);
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton12);
        buttonGroup.add(jRadioButton3);
        buttonGroup.add(jRadioButton4);
        buttonGroup.add(jRadioButton5);
        buttonGroup.add(jRadioButton6);
        buttonGroup.add(jRadioButton7);
        buttonGroup.add(jRadioButton8);
        buttonGroup.add(jRadioButton9);
        buttonGroup.add(jRadioButton10);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbbrechenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAbbrechenActionPerformed

    private void jButtonDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDruckenActionPerformed
        int iSpalte = 0;
        int iZeile = 0;
        int Sp[] = {0,13, 296, 580};                       // Spaltenbreite  283 Pt
        int Ze[] = {0,  795, //  1  2
                        672, //  3  4
                        549, //  5  6
                        420, //  7  8
                        297, //  9 10 
                        170, // 11 12
                        55}; // Zeilenhöhe     123 - 124 Pt

        if (jRadioButton1.isSelected()) {
            iSpalte = 1;   iZeile = 1; 
        } else if (jRadioButton2.isSelected()) {
            iSpalte = 2;   iZeile = 1; 
        } else if (jRadioButton3.isSelected()) {
            iSpalte = 1;   iZeile = 2; 
        } else if (jRadioButton4.isSelected()) {
            iSpalte = 2;   iZeile = 2; 
        } else if (jRadioButton5.isSelected()) {
            iSpalte = 1;   iZeile = 3; 
        } else if (jRadioButton6.isSelected()) {
            iSpalte = 2;   iZeile = 3; 
        } else if (jRadioButton7.isSelected()) {
            iSpalte = 1;   iZeile = 4; 
        } else if (jRadioButton8.isSelected()) {
            iSpalte = 2;   iZeile = 4; 
        } else if (jRadioButton9.isSelected()) {
            iSpalte = 1;   iZeile = 5; 
        } else if (jRadioButton10.isSelected()) {
            iSpalte = 2;   iZeile = 5; 
        } else if (jRadioButton11.isSelected()) {
            iSpalte = 1;   iZeile = 6; 
        } else if (jRadioButton12.isSelected()) {
            iSpalte = 2;   iZeile = 6; 
        }        
            
        try {                                               
            // TODO add your handling code here:
            String outputFileName = ModulHelferlein.pathRechnungen + "\\Etikett.pdf";
            
            // Create a document and add a page to it
            PDDocument document = new PDDocument();
            PDPage page = new PDPage(A4);
            document.addPage(page);
            
            // Create a new font object selecting one of the PDF base fonts
            PDFont fontPlain = PDType1Font.HELVETICA;
            PDFont fontBold = PDType1Font.HELVETICA_BOLD;
            PDFont fontItalic = PDType1Font.HELVETICA_OBLIQUE;
            //        PDFont fontMono = PDType1Font.COURIER;
            
             
            // Start a new content stream which will "hold" the to be created content
            PDPageContentStream cos = new PDPageContentStream(document, page);

            // prüfen jeweils die Länge der Zeile und baue zeilenweise die Adresse  
            if (fontBold.getStringWidth(Zeile[1]) / 1000 * 14 > 270) {
                
            }

            AusgabeLB(cos, fontBold, 14, Color.BLACK, Sp[iSpalte] + 9, Ze[iZeile] - 18, Zeile[1]);
            AusgabeLB(cos, fontBold, 14, Color.BLACK, Sp[iSpalte] + 9, Ze[iZeile] - 36, Zeile[2]);
            AusgabeLB(cos, fontBold, 14, Color.BLACK, Sp[iSpalte] + 9, Ze[iZeile] - 54, Zeile[3]);
            AusgabeLB(cos, fontBold, 14, Color.BLACK, Sp[iSpalte] + 9, Ze[iZeile] - 72, Zeile[4]);
            AusgabeLB(cos, fontBold, 14, Color.BLACK, Sp[iSpalte] + 9, Ze[iZeile] - 90, Zeile[5]);
            AusgabeLB(cos, fontBold, 14, Color.BLACK, Sp[iSpalte] + 9, Ze[iZeile] - 108, Zeile[6]);
            
            // Make sure that the content stream is closed:
            cos.close();
            
            // Save the results and ensure that the document is properly closed:
            document.save(outputFileName);
            document.close();
            
            try {
                Runtime.getRuntime().exec("cmd.exe /c " + "\"" + outputFileName + "\"");
            } catch (IOException exept) {
                ModulHelferlein.Fehlermeldung("Ausgabe Etikett: Exception: " + exept.getMessage());
            }// try Brief ausgeben
        } catch (IOException ex) {
            ModulHelferlein.Fehlermeldung("Ausgabe Etikett: IO-Exception: " + ex.getMessage());
            //Logger.getLogger(_DlgAdresseDrucken.class.getName()).log(Level.SEVERE, null, ex);
        }// try Brief ausgeben
        this.dispose();
    }//GEN-LAST:event_jButtonDruckenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Zeile[1] = "";
        Zeile[2] = "";
        Zeile[3] = "";
        Zeile[4] = "";
        Zeile[5] = "";
        Zeile[6] = "";
        
        Integer ZeilenNr = 1;
        for (int i = 0; i<6; i++) {
            if (!args[i].equals("")) {
                Zeile[ZeilenNr] = args[i];
                ZeilenNr = ZeilenNr + 1;
            }
        }

        System.out.println("Drucke Adresse für " + Zeile[1] + ", " + Zeile[2] + ", " + Zeile[3] + ", " + Zeile[4] + ", " + Zeile[5] + ", " + Zeile[6]);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
        //    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        //        if ("Nimbus".equals(info.getName())) {
        //            javax.swing.UIManager.setLookAndFeel(info.getClassName());
        //            break;
        //        }
        //    }
        //} catch (ClassNotFoundException ex) {
        //    java.util.logging.Logger.getLogger(_DlgAdresseDrucken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
        //    java.util.logging.Logger.getLogger(_DlgAdresseDrucken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
        //    java.util.logging.Logger.getLogger(_DlgAdresseDrucken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //    java.util.logging.Logger.getLogger(_DlgAdresseDrucken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgAdresseDrucken dialog = new _DlgAdresseDrucken(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    //System.exit(0);
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel1;
    private JButton jButtonDrucken;
    private JButton jButtonAbbrechen;
    private JRadioButton jRadioButton11;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton12;
    private JRadioButton jRadioButton2;
    private JRadioButton jRadioButton3;
    private JRadioButton jRadioButton4;
    private JRadioButton jRadioButton5;
    private JRadioButton jRadioButton6;
    private JRadioButton jRadioButton7;
    private JRadioButton jRadioButton8;
    private JRadioButton jRadioButton9;
    private JRadioButton jRadioButton10;
    private JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private static String[] Zeile = {"", "", "", "", "", "", ""};
    private ButtonGroup buttonGroup = new ButtonGroup();
}
