/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author Thomas Zimmermann
 */
public class _DlgMahnungNr extends javax.swing.JDialog {

    /**
     * Creates new form _DlgMahnungNr
     *
     * @param parent
     * @param modal
     */
    public _DlgMahnungNr(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroupAusgabeformat.add(jRadioButtonPDF);
        buttonGroupAusgabeformat.add(jRadioButtonDOC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jButtonDrucken = new JButton();
        jButtonSchliessen = new JButton();
        jLabelMahnungNr = new JLabel();
        jLabelAusgabeformat = new JLabel();
        jRadioButtonPDF = new JRadioButton();
        jRadioButtonDOC = new JRadioButton();
        jTextFieldMahnung = new JTextField();
        jLabel1 = new JLabel();
        jRadioButtonXML = new JRadioButton();
        jRadioButtonHybrid = new JRadioButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ausgabe von Mahnungen");
        setResizable(false);
        Container contentPane = getContentPane();

        //======== panel1 ========
        {

            //---- jButtonDrucken ----
            jButtonDrucken.setText("Drucken");
            jButtonDrucken.setToolTipText("Ausgabe der Mahnung im gew\u00e4hlten Format");
            jButtonDrucken.addActionListener(e -> jButtonDruckenActionPerformed(e));

            //---- jButtonSchliessen ----
            jButtonSchliessen.setText("Schlie\u00dfen");
            jButtonSchliessen.setToolTipText("Schlie\u00dfen des Dialoges ohne Ausgabe");
            jButtonSchliessen.addActionListener(e -> jButtonSchliessenActionPerformed(e));

            //---- jLabelMahnungNr ----
            jLabelMahnungNr.setText("Mahnung Nr.");

            //---- jLabelAusgabeformat ----
            jLabelAusgabeformat.setText("Ausgabeformat");

            //---- jRadioButtonPDF ----
            jRadioButtonPDF.setSelected(true);
            jRadioButtonPDF.setText("PDF");
            jRadioButtonPDF.setToolTipText("Ausgabe der Mahnung als PDF-Dokument");

            //---- jRadioButtonDOC ----
            jRadioButtonDOC.setText("DOC");
            jRadioButtonDOC.setToolTipText("Ausgabe der Mahnung als Word-Dokument");

            //---- jTextFieldMahnung ----
            jTextFieldMahnung.setToolTipText("Eingabe der Nummer der Mahnung");
            jTextFieldMahnung.addActionListener(e -> jTextFieldMahnungActionPerformed(e));

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel1.setText("Mahnung erzeugen");

            //---- jRadioButtonXML ----
            jRadioButtonXML.setText("XML");

            //---- jRadioButtonHybrid ----
            jRadioButtonHybrid.setText("Hybrid");

            GroupLayout panel1Layout = new GroupLayout(panel1);
            panel1.setLayout(panel1Layout);
            panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jLabel1)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabelMahnungNr)
                                .addGap(117, 117, 117)
                                .addComponent(jLabelAusgabeformat))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldMahnung, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jRadioButtonPDF))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jRadioButtonDOC))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jRadioButtonXML))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jRadioButtonHybrid))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jButtonDrucken)
                                .addGap(14, 14, 14)
                                .addComponent(jButtonSchliessen)))
                        .addContainerGap(25, Short.MAX_VALUE))
            );
            panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jLabelMahnungNr)
                            .addComponent(jLabelAusgabeformat))
                        .addGap(10, 10, 10)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextFieldMahnung, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonPDF))
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonDOC)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonXML)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonHybrid)
                        .addGap(19, 19, 19)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jButtonDrucken)
                            .addComponent(jButtonSchliessen))
                        .addContainerGap(20, Short.MAX_VALUE))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        setSize(290, 260);
        setLocationRelativeTo(getOwner());

        //---- buttonGroup1 ----
        ButtonGroup buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(jRadioButtonPDF);
        buttonGroup1.add(jRadioButtonDOC);
        buttonGroup1.add(jRadioButtonXML);
        buttonGroup1.add(jRadioButtonHybrid);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDruckenActionPerformed
        // TODO add your handling code here:
        try {
            if (jRadioButtonPDF.isSelected()) {
                briefRechnungMahnung.briefPDF(RechNr, 99, jTextFieldMahnung.getText(),0);
            } else if (jRadioButtonXML.isSelected()) {
                briefRechnungMahnung.briefPDF(RechNr, 99, jTextFieldMahnung.getText(),1);
            } else if (jRadioButtonHybrid.isSelected()) {
                briefRechnungMahnung.briefPDF(RechNr, 99, jTextFieldMahnung.getText(),2);
            } else {
                briefRechnungMahnung.briefDOC(RechNr, 99, jTextFieldMahnung.getText());
            }
        } catch (Exception e) {
            Modulhelferlein.Fehlermeldung("Exception: " + e.getMessage());
        }
        // Schließen des Dialoges
        this.dispose();
    }//GEN-LAST:event_jButtonDruckenActionPerformed

    private void jButtonSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSchliessenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSchliessenActionPerformed

    private void jTextFieldMahnungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMahnungActionPerformed
        // TODO add your handling code here:
        if (Modulhelferlein.checkNumberFormatInt(jTextFieldMahnung.getText()) < 0) {
            Modulhelferlein.Infomeldung("fehlerhafte Eingabe - die ist keine korrekte Ganzzahl");
        }
    }//GEN-LAST:event_jTextFieldMahnungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /**
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
         * } catch (ClassNotFoundException | InstantiationException |
         * IllegalAccessException | javax.swing.UnsupportedLookAndFeelException
         * ex) {
         * java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); }
         */
        //</editor-fold>

        //</editor-fold>
        RechNr = args[0];
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgMahnungNr dialog = new _DlgMahnungNr(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JButton jButtonDrucken;
    private JButton jButtonSchliessen;
    private JLabel jLabelMahnungNr;
    private JLabel jLabelAusgabeformat;
    private JRadioButton jRadioButtonPDF;
    private JRadioButton jRadioButtonDOC;
    private JTextField jTextFieldMahnung;
    private JLabel jLabel1;
    private JRadioButton jRadioButtonXML;
    private JRadioButton jRadioButtonHybrid;
    // End of variables declaration//GEN-END:variables
    private static String RechNr;
    private ButtonGroup buttonGroupAusgabeformat = new ButtonGroup();
}
