/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import net.miginfocom.swing.*;

/**
 * Die Klasse _DlgUeber stellt den Dialog zur Information zur Software sowie
 * Copyright und Programmierer bereit
 *
 * @author Thomas Zimmermann
 */
public class _DlgUeber extends javax.swing.JDialog {

    /**
     * Creates new form _DlgUeber
     *
     * @param parent
     * @param modal
     */
    public _DlgUeber(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jBtnSchliessen = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        logo = new JButton();
        jLabel4 = new JLabel();
        jLabel3 = new JLabel();
        label1 = new JLabel();
        jLblEMailData1 = new JLabel();
        label2 = new JLabel();
        jLblEMailData2 = new JLabel();
        jLblEMail = new JLabel();
        jLblEMailData = new JLabel();
        jLblTelefon = new JLabel();
        jLblTelefonData = new JLabel();
        jLblTelefax = new JLabel();
        jLblTelefaxData = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("\u00dcber");
        setModal(true);
        setResizable(false);
        setFont(this.getFont().deriveFont(this.getFont().getStyle() | Font.BOLD));
        Container contentPane = getContentPane();

        //======== panel1 ========
        {
            panel1.setLayout(new MigLayout(
                "insets 0,hidemode 3,gap 5 5",
                // columns
                "[fill]" +
                "[fill]" +
                "[fill]",
                // rows
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[]"));

            //---- jBtnSchliessen ----
            jBtnSchliessen.setText("Schlie\u00dfen");
            jBtnSchliessen.setToolTipText("Schlie\u00dft den Dialog");
            jBtnSchliessen.addActionListener(e -> jBtnSchliessenActionPerformed(e));
            panel1.add(jBtnSchliessen, "cell 0 11 2 1");

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 18));
            jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
            jLabel1.setText("Carola Hartmann Miles Verlag");
            panel1.add(jLabel1, "cell 0 0 2 1");

            //---- jLabel2 ----
            jLabel2.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
            jLabel2.setText("Verlagsverwaltung");
            jLabel2.setToolTipText("");
            panel1.add(jLabel2, "cell 0 1 2 1");

            //---- logo ----
            logo.setIcon(new ImageIcon(getClass().getResource("/milesVerlagMain/logo.png")));
            logo.setBorderPainted(false);
            logo.setFocusPainted(false);
            logo.setFocusable(false);
            logo.setPreferredSize(new Dimension(400, 100));
            logo.setRequestFocusEnabled(false);
            logo.setSelectedIcon(new ImageIcon(getClass().getResource("/milesVerlagMain/logo.png")));
            logo.setVerifyInputWhenFocusTarget(false);
            panel1.add(logo, "cell 0 4 2 1");

            //---- jLabel4 ----
            jLabel4.setText("(c) 2017   EDV-Beratung und Betrieb, Entwicklung von Software");
            jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
            panel1.add(jLabel4, "cell 0 2 2 1");

            //---- jLabel3 ----
            jLabel3.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel3.setText("Dipl. Inform. Thomas Zimmermann ");
            jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
            panel1.add(jLabel3, "cell 1 3 2 1");

            //---- label1 ----
            label1.setText("Stra\u00dfe");
            label1.setHorizontalAlignment(SwingConstants.RIGHT);
            panel1.add(label1, "cell 0 5");

            //---- jLblEMailData1 ----
            jLblEMailData1.setText("Ritterfelddamm 225");
            jLblEMailData1.setHorizontalAlignment(SwingConstants.LEFT);
            panel1.add(jLblEMailData1, "cell 1 5");

            //---- label2 ----
            label2.setText("Ort");
            label2.setHorizontalAlignment(SwingConstants.RIGHT);
            panel1.add(label2, "cell 0 6");

            //---- jLblEMailData2 ----
            jLblEMailData2.setText("14089 Berlin");
            panel1.add(jLblEMailData2, "cell 1 6");

            //---- jLblEMail ----
            jLblEMail.setText("e-Mail");
            jLblEMail.setHorizontalAlignment(SwingConstants.RIGHT);
            panel1.add(jLblEMail, "cell 0 8");

            //---- jLblEMailData ----
            jLblEMailData.setText("kontakt@edv-beratung.familiezimmermann.de");
            panel1.add(jLblEMailData, "cell 1 8");

            //---- jLblTelefon ----
            jLblTelefon.setText("Telefon");
            jLblTelefon.setHorizontalAlignment(SwingConstants.RIGHT);
            panel1.add(jLblTelefon, "cell 0 9");

            //---- jLblTelefonData ----
            jLblTelefonData.setText("(030) 37 43 51 10");
            panel1.add(jLblTelefonData, "cell 1 9");

            //---- jLblTelefax ----
            jLblTelefax.setText("Telefax");
            jLblTelefax.setHorizontalAlignment(SwingConstants.RIGHT);
            panel1.add(jLblTelefax, "cell 0 10");

            //---- jLblTelefaxData ----
            jLblTelefaxData.setText("(030) 37 43 51 09");
            panel1.add(jLblTelefaxData, "cell 1 10");
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, 429, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, 336, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(6, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Schließt den Dialog
     *
     * @param evt
     */
    private void jBtnSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSchliessenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSchliessenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/**        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
*/        
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgUeber dialog = new _DlgUeber(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JButton jBtnSchliessen;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JButton logo;
    private JLabel jLabel4;
    private JLabel jLabel3;
    private JLabel label1;
    private JLabel jLblEMailData1;
    private JLabel label2;
    private JLabel jLblEMailData2;
    private JLabel jLblEMail;
    private JLabel jLblEMailData;
    private JLabel jLblTelefon;
    private JLabel jLblTelefonData;
    private JLabel jLblTelefax;
    private JLabel jLblTelefaxData;
    // End of variables declaration//GEN-END:variables
}
