/*
 * Copyright (C) 2018 thoma
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package milesVerlagMain;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author thoma
 */
public class _DlgInventur extends javax.swing.JDialog {

    /**
     * Creates new form _DlgInventur
     * @param parent
     * @param modal
     */
    public _DlgInventur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jRadioButtonAutor = new JRadioButton();
        jRadioButtonISBN = new JRadioButton();
        jRadioButtonPDF = new JRadioButton();
        jRadioButtonXLS = new JRadioButton();
        jRadioButtonDOC = new JRadioButton();
        jButtonDrucken = new JButton();
        jButtonAbbrechen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles Verlag");
        Container contentPane = getContentPane();

        //======== panel1 ========
        {

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel1.setText("Inventur");

            //---- jLabel2 ----
            jLabel2.setText("Sortierung");

            //---- jLabel3 ----
            jLabel3.setText("Format");

            //---- jRadioButtonAutor ----
            jRadioButtonAutor.setSelected(true);
            jRadioButtonAutor.setText("Autor");

            //---- jRadioButtonISBN ----
            jRadioButtonISBN.setText("ISBN");

            //---- jRadioButtonPDF ----
            jRadioButtonPDF.setSelected(true);
            jRadioButtonPDF.setText("PDF");

            //---- jRadioButtonXLS ----
            jRadioButtonXLS.setText("XLS");

            //---- jRadioButtonDOC ----
            jRadioButtonDOC.setText("DOC");

            //---- jButtonDrucken ----
            jButtonDrucken.setText("Drucken");
            jButtonDrucken.addActionListener(e -> jButtonDruckenActionPerformed(e));

            //---- jButtonAbbrechen ----
            jButtonAbbrechen.setText("Abbrechen");
            jButtonAbbrechen.addActionListener(e -> jButtonAbbrechenActionPerformed(e));

            GroupLayout panel1Layout = new GroupLayout(panel1);
            panel1.setLayout(panel1Layout);
            panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jLabel1)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel3))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAutor)
                                .addGap(108, 108, 108)
                                .addComponent(jRadioButtonPDF))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonISBN)
                                .addGap(112, 112, 112)
                                .addComponent(jRadioButtonXLS))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jRadioButtonDOC))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jButtonDrucken)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAbbrechen)))
                        .addContainerGap(25, Short.MAX_VALUE))
            );
            panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButtonAutor)
                            .addComponent(jRadioButtonPDF))
                        .addGap(3, 3, 3)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButtonISBN)
                            .addComponent(jRadioButtonXLS))
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButtonDOC)
                        .addGap(34, 34, 34)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jButtonDrucken)
                            .addComponent(jButtonAbbrechen))
                        .addContainerGap(23, Short.MAX_VALUE))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(getOwner());

        //---- buttonGroupSortierung ----
        ButtonGroup buttonGroupSortierung = new ButtonGroup();
        buttonGroupSortierung.add(jRadioButtonAutor);
        buttonGroupSortierung.add(jRadioButtonISBN);

        //---- buttonGroupFormat ----
        ButtonGroup buttonGroupFormat = new ButtonGroup();
        buttonGroupFormat.add(jRadioButtonPDF);
        buttonGroupFormat.add(jRadioButtonXLS);
        buttonGroupFormat.add(jRadioButtonDOC);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDruckenActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPDF.isSelected()) {
            if (jRadioButtonAutor.isSelected()) {
                berBuchbestand.berichtPDF("AUTOR");
            } else {
                berBuchbestand.berichtPDF("ISBN"); 
            }
        } else if (jRadioButtonXLS.isSelected()) {
            if (jRadioButtonAutor.isSelected()) {
                berBuchbestand.berichtXLS("AUTOR");
            } else {
                berBuchbestand.berichtXLS("ISBN"); 
            }
        } else {
            Modulhelferlein.Infomeldung("Ausgabe DOC","Funktion noch nicht implementiert");
        }
        this.dispose();
    }//GEN-LAST:event_jButtonDruckenActionPerformed

    private void jButtonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbbrechenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAbbrechenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       // try {
       //     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
       //         if ("Nimbus".equals(info.getName())) {
       //             javax.swing.UIManager.setLookAndFeel(info.getClassName());
       //             break;
       //         }
       //     }
       // } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
       //     java.util.logging.Logger.getLogger(_DlgInventur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgInventur dialog = new _DlgInventur(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JRadioButton jRadioButtonAutor;
    private JRadioButton jRadioButtonISBN;
    private JRadioButton jRadioButtonPDF;
    private JRadioButton jRadioButtonXLS;
    private JRadioButton jRadioButtonDOC;
    private JButton jButtonDrucken;
    private JButton jButtonAbbrechen;
    // End of variables declaration//GEN-END:variables
}
