/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Thomas Zimmermann
 */
public class _DlgTabellenLeeren extends javax.swing.JDialog {

    /**
     * Creates new form _DlgTabellenErstellen
     *
     * @param parent
     * @param modal
     */
    public _DlgTabellenLeeren(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Datenbank-Treiber laden
        try {
            Class.forName(Modulhelferlein.dbDriver);
        } catch (ClassNotFoundException exept) {
            Modulhelferlein.Fehlermeldung("Tabelle leeren",
                    "ClassNotFoundException: Treiber nicht gefunden: "
                    , exept.getMessage());
        }

        // Verbindung zur Datenbank über die JDBC-Brücke
        try {
            conn = DriverManager.getConnection(Modulhelferlein.dbUrl, Modulhelferlein.dbUser, Modulhelferlein.dbPassword);
        } catch (SQLException exept) {
            Modulhelferlein.Fehlermeldung("Tabelle leeren",
                    "SQL-Excetion: Verbindung nicht moeglich: "
                    , exept.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel4 = new JLabel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jCheckBox2 = new JCheckBox();
        jCheckBox6 = new JCheckBox();
        jCheckBox10 = new JCheckBox();
        jCheckBox1 = new JCheckBox();
        jCheckBox5 = new JCheckBox();
        jCheckBox11 = new JCheckBox();
        jCheckBox3 = new JCheckBox();
        jCheckBox7 = new JCheckBox();
        jCheckBox12 = new JCheckBox();
        jCheckBox4 = new JCheckBox();
        jCheckBox14 = new JCheckBox();
        jCheckBox13 = new JCheckBox();
        jCheckBox15 = new JCheckBox();
        jCheckBox16 = new JCheckBox();
        jCheckBox8 = new JCheckBox();
        jCheckBox18 = new JCheckBox();
        jCheckBox9 = new JCheckBox();
        jCheckBox17 = new JCheckBox();
        jCheckBox19 = new JCheckBox();
        jButtonEnde = new JButton();
        jButtonSchliessen = new JButton();
        jCheckBox20 = new JCheckBox();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles Verlag");
        setResizable(false);
        setFont(new Font("Dialog", Font.BOLD, 12));
        setMinimumSize(new Dimension(560, 400));
        Container contentPane = getContentPane();
        contentPane.setLayout(null);

        //======== panel1 ========
        {
            panel1.setMinimumSize(new Dimension(560, 400));
            panel1.setLayout(null);

            //---- jLabel4 ----
            jLabel4.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel4.setText("Leeren von Tabellen");
            panel1.add(jLabel4);
            jLabel4.setBounds(new Rectangle(new Point(0, 0), jLabel4.getPreferredSize()));

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 11));
            jLabel1.setText("Stammdaten");
            jLabel1.setToolTipText("");
            panel1.add(jLabel1);
            jLabel1.setBounds(new Rectangle(new Point(0, 45), jLabel1.getPreferredSize()));

            //---- jLabel2 ----
            jLabel2.setFont(new Font("Tahoma", Font.BOLD, 11));
            jLabel2.setText("Bewegungsdaten");
            jLabel2.setToolTipText("");
            panel1.add(jLabel2);
            jLabel2.setBounds(127, 45, 177, jLabel2.getPreferredSize().height);

            //---- jLabel3 ----
            jLabel3.setFont(new Font("Tahoma", Font.BOLD, 11));
            jLabel3.setText("Sonstige Daten");
            jLabel3.setToolTipText("");
            panel1.add(jLabel3);
            jLabel3.setBounds(309, 45, 159, jLabel3.getPreferredSize().height);

            //---- jCheckBox2 ----
            jCheckBox2.setText("Buchprojekte");
            panel1.add(jCheckBox2);
            jCheckBox2.setBounds(0, 64, 122, jCheckBox2.getPreferredSize().height);

            //---- jCheckBox6 ----
            jCheckBox6.setText("Einnahmen");
            panel1.add(jCheckBox6);
            jCheckBox6.setBounds(127, 64, 177, jCheckBox6.getPreferredSize().height);

            //---- jCheckBox10 ----
            jCheckBox10.setText("Konfiguration");
            panel1.add(jCheckBox10);
            jCheckBox10.setBounds(309, 64, 159, jCheckBox10.getPreferredSize().height);

            //---- jCheckBox1 ----
            jCheckBox1.setText("Adressen");
            panel1.add(jCheckBox1);
            jCheckBox1.setBounds(0, 92, 74, jCheckBox1.getPreferredSize().height);

            //---- jCheckBox5 ----
            jCheckBox5.setText("Ausgaben");
            panel1.add(jCheckBox5);
            jCheckBox5.setBounds(127, 92, 177, jCheckBox5.getPreferredSize().height);

            //---- jCheckBox11 ----
            jCheckBox11.setText("Termine");
            panel1.add(jCheckBox11);
            jCheckBox11.setBounds(309, 92, 159, jCheckBox11.getPreferredSize().height);

            //---- jCheckBox3 ----
            jCheckBox3.setText("Mailverteiler");
            panel1.add(jCheckBox3);
            jCheckBox3.setBounds(0, 120, 122, jCheckBox3.getPreferredSize().height);

            //---- jCheckBox7 ----
            jCheckBox7.setText("Bestellungen");
            panel1.add(jCheckBox7);
            jCheckBox7.setBounds(127, 120, 177, jCheckBox7.getPreferredSize().height);

            //---- jCheckBox12 ----
            jCheckBox12.setText("Bestellnummer");
            panel1.add(jCheckBox12);
            jCheckBox12.setBounds(309, 120, 159, jCheckBox12.getPreferredSize().height);

            //---- jCheckBox4 ----
            jCheckBox4.setText("Mailadressen");
            panel1.add(jCheckBox4);
            jCheckBox4.setBounds(0, 148, 122, jCheckBox4.getPreferredSize().height);

            //---- jCheckBox14 ----
            jCheckBox14.setText("Rezensionen ausgehend");
            panel1.add(jCheckBox14);
            jCheckBox14.setBounds(127, 148, 177, jCheckBox14.getPreferredSize().height);

            //---- jCheckBox13 ----
            jCheckBox13.setText("Umsatzsteuervoranmeldung");
            panel1.add(jCheckBox13);
            jCheckBox13.setBounds(new Rectangle(new Point(309, 148), jCheckBox13.getPreferredSize()));

            //---- jCheckBox15 ----
            jCheckBox15.setText("Rezensionen Details ausg...");
            panel1.add(jCheckBox15);
            jCheckBox15.setBounds(new Rectangle(new Point(127, 176), jCheckBox15.getPreferredSize()));

            //---- jCheckBox16 ----
            jCheckBox16.setText("Hilfstabelle Buch");
            panel1.add(jCheckBox16);
            jCheckBox16.setBounds(309, 176, 159, jCheckBox16.getPreferredSize().height);

            //---- jCheckBox8 ----
            jCheckBox8.setText("Rezensionen eingehend");
            panel1.add(jCheckBox8);
            jCheckBox8.setBounds(127, 204, 177, jCheckBox8.getPreferredSize().height);

            //---- jCheckBox18 ----
            jCheckBox18.setText("Aufgaben");
            panel1.add(jCheckBox18);
            jCheckBox18.setBounds(309, 204, 159, jCheckBox18.getPreferredSize().height);

            //---- jCheckBox9 ----
            jCheckBox9.setText("Bestellungdetails");
            panel1.add(jCheckBox9);
            jCheckBox9.setBounds(127, 232, 177, jCheckBox9.getPreferredSize().height);

            //---- jCheckBox17 ----
            jCheckBox17.setText("Honorar");
            panel1.add(jCheckBox17);
            jCheckBox17.setBounds(309, 232, 159, jCheckBox17.getPreferredSize().height);

            //---- jCheckBox19 ----
            jCheckBox19.setText("Hilfstabelle Verkauf");
            panel1.add(jCheckBox19);
            jCheckBox19.setBounds(309, 260, 159, jCheckBox19.getPreferredSize().height);

            //---- jButtonEnde ----
            jButtonEnde.setText("Leeren");
            jButtonEnde.addActionListener(e -> jButtonEndeActionPerformed(e));
            panel1.add(jButtonEnde);
            jButtonEnde.setBounds(125, 325, 177, jButtonEnde.getPreferredSize().height);

            //---- jButtonSchliessen ----
            jButtonSchliessen.setText("Schlie\u00dfen");
            jButtonSchliessen.addActionListener(e -> jButtonSchliessenActionPerformed(e));
            panel1.add(jButtonSchliessen);
            jButtonSchliessen.setBounds(310, 325, 159, jButtonSchliessen.getPreferredSize().height);

            //---- jCheckBox20 ----
            jCheckBox20.setText("Benutzer");
            panel1.add(jCheckBox20);
            jCheckBox20.setBounds(309, 285, 69, 23);

            { // compute preferred size
                Dimension preferredSize = new Dimension();
                for(int i = 0; i < panel1.getComponentCount(); i++) {
                    Rectangle bounds = panel1.getComponent(i).getBounds();
                    preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                    preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
                }
                Insets insets = panel1.getInsets();
                preferredSize.width += insets.right;
                preferredSize.height += insets.bottom;
                panel1.setMinimumSize(preferredSize);
                panel1.setPreferredSize(preferredSize);
            }
        }
        contentPane.add(panel1);
        panel1.setBounds(10, 11, 470, 354);

        { // compute preferred size
            Dimension preferredSize = new Dimension();
            for(int i = 0; i < contentPane.getComponentCount(); i++) {
                Rectangle bounds = contentPane.getComponent(i).getBounds();
                preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
            }
            Insets insets = contentPane.getInsets();
            preferredSize.width += insets.right;
            preferredSize.height += insets.bottom;
            contentPane.setMinimumSize(preferredSize);
            contentPane.setPreferredSize(preferredSize);
        }
        setSize(495, 410);
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndeActionPerformed
        // TODO add your handling code here:
        if (conn != null) {
            try {
                SQLAnfrage = conn.createStatement();
            } catch (SQLException ex) {
                Modulhelferlein.Fehlermeldung("SQL-Exception", "Leeren der Tabellen", ex.getMessage());
            }
            if (JOptionPane.showConfirmDialog(null,
                    "Sollen die Tabellen wirklich geleert werden?",
                    "Bestätigung",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    if (jCheckBox19.isSelected()) {
                        SQL = "DELETE FROM TBL_VERKAUF";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle VERKAUF wurde geleert");
                    }
                    if (jCheckBox9.isSelected()) {
                        SQL = "DELETE FROM TBL_BESTELLUNG_DETAIL";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle BESTELLUNG_DETAIL wurde geleert");
                    }
                    if (jCheckBox5.isSelected()) {
                        SQL = "DELETE FROM TBL_AUSGABEN";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle AUSGABEN wurde geleert");
                    }
                    if (jCheckBox7.isSelected()) {
                        SQL = "DELETE FROM TBL_BESTELLUNG";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle BESTELLUNG wurde geleert");
                    }
                    if (jCheckBox6.isSelected()) {
                        SQL = "DELETE FROM TBL_EINNAHMEN";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle EINNAHMEN wurde geleert");
                    }
                    if (jCheckBox13.isSelected()) {
                        SQL = "DELETE FROM TBL_USTVA";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle USTVA wurde geleert");
                    }
                    if (jCheckBox20.isSelected()) {
                        SQL = "DELETE FROM TBL_BENUTZER";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle BENUTZER wurde geleert");
                    }
                    if (jCheckBox1.isSelected()) {
                        SQL = "DELETE FROM TBL_ADRESSE";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle ADRESSE wurde geleert");
                    }
                    if (jCheckBox2.isSelected()) {
                        SQL = "DELETE FROM TBL_BUCH";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle BUCH wurde geleert");
                    }
                    if (jCheckBox8.isSelected()) {
                        SQL = "DELETE FROM TBL_REZENSION";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle REZENSION wurde geleert");
                    }
                    if (jCheckBox11.isSelected()) {
                        SQL = "DELETE FROM TBL_TERMINE";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle TERMINE wurde geleert");
                    }
                    if (jCheckBox12.isSelected()) {
                        SQL = "DELETE FROM TBL_BESTELLNR";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle BESTELLNR wurde geleert");
                    }
                    if (jCheckBox3.isSelected()) {
                        SQL = "DELETE FROM TBL_MAILVERTEILER";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle MAILVERTEILER wurde geleert");
                    }
                    if (jCheckBox4.isSelected()) {
                        SQL = "DELETE FROM TBL_MAILADRESSE";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle MAILADRESSE wurde geleert");
                    }
                    if (jCheckBox14.isSelected()) {
                        SQL = "DELETE FROM TBL_REZENSIONEN_AUS";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle Rezensionen ausgehend wurde geleert");
                    }
                    if (jCheckBox15.isSelected()) {
                        SQL = "DELETE FROM TBL_REZENSIONEN_AUS_DETAIL";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle Rezensionen ausgehend Details wurde geleert");
                    }
                    if (jCheckBox16.isSelected()) {
                        SQL = "DELETE FROM TBL_HILFE_BUCH";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle Hilfe Buch wurde geleert");
                    }
                    if (jCheckBox17.isSelected()) {
                        SQL = "DELETE FROM TBL_HONORAR";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle Honorar wurde geleert");
                    }
                    if (jCheckBox18.isSelected()) {
                        SQL = "DELETE FROM TBL_AUFGABEN";
                        SQLAnfrage.executeUpdate(SQL);
                        Modulhelferlein.Infomeldung("Tabelle AUFGABEN wurde geleert");
                    }
                } catch (SQLException exept) {
                    Modulhelferlein.Fehlermeldung("Tabelle leeren",
                            "Leeren der Tabellen nicht möglich:" , exept.getMessage());
                }
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButtonEndeActionPerformed

    private void jButtonSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSchliessenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSchliessenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/**        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
*/        
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgTabellenLeeren dialog = new _DlgTabellenLeeren(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    private Connection conn;
    private Statement SQLAnfrage;

    private String SQL;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel4;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JCheckBox jCheckBox2;
    private JCheckBox jCheckBox6;
    private JCheckBox jCheckBox10;
    private JCheckBox jCheckBox1;
    private JCheckBox jCheckBox5;
    private JCheckBox jCheckBox11;
    private JCheckBox jCheckBox3;
    private JCheckBox jCheckBox7;
    private JCheckBox jCheckBox12;
    private JCheckBox jCheckBox4;
    private JCheckBox jCheckBox14;
    private JCheckBox jCheckBox13;
    private JCheckBox jCheckBox15;
    private JCheckBox jCheckBox16;
    private JCheckBox jCheckBox8;
    private JCheckBox jCheckBox18;
    private JCheckBox jCheckBox9;
    private JCheckBox jCheckBox17;
    private JCheckBox jCheckBox19;
    private JButton jButtonEnde;
    private JButton jButtonSchliessen;
    private JCheckBox jCheckBox20;
    // End of variables declaration//GEN-END:variables
}
