/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */



package milesVerlagMain;

//~--- non-JDK imports --------------------------------------------------------

import net.miginfocom.swing.*;

//~--- JDK imports ------------------------------------------------------------

import java.awt.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;

import javax.mail.Address;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JFileChooser;

/**
 *
 * @author Thomas Zimmermann
 */
public class _DlgMail extends javax.swing.JDialog {
    String Filename = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JTextField field_Subject;
    private JLabel jLabel3;
    private JComboBox<String> field_Verteiler;
    private JLabel jLabel4;
    private JScrollPane jScrollPane1;
    private JTextArea field_Text;
    private JLabel jLabel5;
    private JButton Anhang;
    private JTextField field_Anhang;
    private JButton Senden;
    private JButton Schliessen;
    // End of variables declaration//GEN-END:variables

    Connection                conn;
    Statement                 SQLAnfrage;
    ResultSet                 result;

    /**
     * Creates new form _DlgMail
     *
     * @param parent
     * @param modal
     */
    public _DlgMail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conn = null;

        // Datenbank-Treiber laden
        try {
            Class.forName(Modulhelferlein.dbDriver);
        } catch (ClassNotFoundException exept) {
            Modulhelferlein.Fehlermeldung("Treiber nicht gefunden.");
        }

        // Verbindung zur Datenbank über die JDBC-Brücke
        try {
            conn = DriverManager.getConnection(Modulhelferlein.dbUrl, Modulhelferlein.dbUser,
                                               Modulhelferlein.dbPassword);
        } catch (SQLException exept) {
            Modulhelferlein.Fehlermeldung("Verbindung zur Datenbank nicht moeglich.");
        }

        // final Connection conn2=conn;
        if (conn != null) {
            SQLAnfrage = null;    // Anfrage erzeugen

            try {
                Statement SQLAnfrageVerteiler = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                                    ResultSet.CONCUR_UPDATABLE);
                ResultSet resultVerteiler = SQLAnfrageVerteiler.executeQuery("SELECT * FROM TBL_MAILVERTEILER");

                while (resultVerteiler.next()) {
                    field_Verteiler.addItem(resultVerteiler.getString("MAILVERTEILER_NAME"));
                }
            } catch (SQLException exept) {
                Modulhelferlein.Fehlermeldung("SQLException: SQL-Anfrage nicht moeglich. " + exept.getMessage());
            }    // try
        }        // if
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        field_Subject = new JTextField();
        jLabel3 = new JLabel();
        field_Verteiler = new JComboBox<>();
        jLabel4 = new JLabel();
        jScrollPane1 = new JScrollPane();
        field_Text = new JTextArea();
        jLabel5 = new JLabel();
        Anhang = new JButton();
        field_Anhang = new JTextField();
        Senden = new JButton();
        Schliessen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles Verlag");
        setResizable(false);
        setFont(new Font(Font.DIALOG, Font.BOLD, 12));
        var contentPane = getContentPane();

        //======== panel1 ========
        {
            panel1.setLayout(new MigLayout(
                "insets 0,hidemode 3,gap 5 5",
                // columns
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]",
                // rows
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[fill]" +
                "[]" +
                "[]"));

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel1.setText("Versenden von e-Mails");
            panel1.add(jLabel1, "cell 0 0 4 1");

            //---- jLabel2 ----
            jLabel2.setText("Betreff");
            panel1.add(jLabel2, "cell 0 2");
            panel1.add(field_Subject, "cell 1 2 4 1");

            //---- jLabel3 ----
            jLabel3.setText("Verteiler");
            panel1.add(jLabel3, "cell 0 3");

            //---- field_Verteiler ----
            field_Verteiler.setModel(new DefaultComboBoxModel<>(new String[] {

            }));
            panel1.add(field_Verteiler, "cell 1 3 4 1");

            //---- jLabel4 ----
            jLabel4.setText("Text");
            panel1.add(jLabel4, "cell 0 4");

            //======== jScrollPane1 ========
            {

                //---- field_Text ----
                field_Text.setColumns(20);
                field_Text.setRows(5);
                jScrollPane1.setViewportView(field_Text);
            }
            panel1.add(jScrollPane1, "cell 1 4 4 2");

            //---- jLabel5 ----
            jLabel5.setText("Anhang");
            jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() & ~Font.BOLD));
            panel1.add(jLabel5, "cell 0 6");

            //---- Anhang ----
            Anhang.setText("...");
            Anhang.addActionListener(e -> AnhangActionPerformed(e));
            panel1.add(Anhang, "cell 1 6");
            panel1.add(field_Anhang, "cell 2 6 3 1");

            //---- Senden ----
            Senden.setText("Senden");
            Senden.addActionListener(e -> SendenActionPerformed(e));
            panel1.add(Senden, "cell 2 9 2 1");

            //---- Schliessen ----
            Schliessen.setText("Abbrechen");
            Schliessen.addActionListener(e -> SchliessenActionPerformed(e));
            panel1.add(Schliessen, "cell 4 9");
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, 279, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        setSize(295, 330);
        setLocationRelativeTo(getOwner());
    }    // </editor-fold>//GEN-END:initComponents

    private void SchliessenActionPerformed(java.awt.event.ActionEvent evt) {    // GEN-FIRST:event_SchliessenActionPerformed

        // TODO add your handling code here:
        this.dispose();
    }                                                                       // GEN-LAST:event_SchliessenActionPerformed

    private void SendenActionPerformed(java.awt.event.ActionEvent evt) {    // GEN-FIRST:event_SendenActionPerformed

        // TODO add your handling code here:
        String Verteiler = "";
        String host      = Modulhelferlein.MailHost;
        String port      = Modulhelferlein.MailPort;
        String user      = Modulhelferlein.MailUser;
        String pass      = Modulhelferlein.MailPass;

        // Get system properties
        Properties properties = System.getProperties();

        // Setup mail server
        properties.setProperty("mail.smtp.host", host);
        properties.setProperty("mail.smtp.auth", "true");
        properties.setProperty("mail.port", port);
        properties.setProperty("mail.user", user);
        properties.setProperty("mail.password", pass);

        try {

            // Get the default Session object.
            Session   session   = Session.getDefaultInstance(properties);
            Transport transport = session.getTransport("smtp");

            transport.connect(host, Integer.parseInt(port), user, pass);

            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            message.setFrom(new InternetAddress(user));

            // Set To: header field of the header.
            // message.setRecipient(Message.RecipientType.TO, new InternetAddress(field_To.getText()));
            String  adressliste = "";
            Integer i           = 0;

            result = SQLAnfrage.executeQuery("SELECT * FROM TBL_MAILVERTEILER WHERE MAILVERTEILER_NAME='"
                                             + field_Verteiler.getSelectedItem() + "'");

            if (result.next()) {
                Verteiler = result.getString("MAILVERTEILER_ID");
            } else {
                Verteiler = "0";
            }

            result = SQLAnfrage.executeQuery("SELECT * FROM TBL_MAILADRESSE WHERE MAILADRESSE_ID='" + Verteiler + "'");

            while (result.next()) {
                adressliste = adressliste + "," + result.getString("MAILVERTEILER_NAME");
            }

            Address[] addresses;

            addresses = InternetAddress.parse(adressliste);
            message.setRecipients(Message.RecipientType.TO, addresses);

            // Set Subject: header field
            message.setSubject(field_Subject.getText());

            // Create the message part
            BodyPart messageBodyPart = new MimeBodyPart();

            // Fill the message
            messageBodyPart.setText(field_Text.getText());

            // Create a multipar message
            Multipart multipart = new MimeMultipart();

            // Set text message part
            multipart.addBodyPart(messageBodyPart);

            // Part two is attachment
            if (Filename.length() > 0) {
                messageBodyPart = new MimeBodyPart();

                DataSource source = new FileDataSource(Filename);

                messageBodyPart.setDataHandler(new DataHandler(source));
                messageBodyPart.setFileName(Filename);
                multipart.addBodyPart(messageBodyPart);
            }

            // Send the complete message parts
            message.setContent(multipart);
            transport.sendMessage(message, addresses);
            Modulhelferlein.Infomeldung("Mail wurde gesendet");
            transport.close();
        } catch (MessagingException mex) {}
        catch (SQLException ex) {
            Logger.getLogger(_DlgMail.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();
    }                                                                       // GEN-LAST:event_SendenActionPerformed

    private void AnhangActionPerformed(java.awt.event.ActionEvent evt) {    // GEN-FIRST:event_AnhangActionPerformed

        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(Modulhelferlein.pathBerichte);

        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int Ergebnis = chooser.showDialog(null, "Anhang wählen");

        if (Ergebnis == JFileChooser.APPROVE_OPTION) {
            Filename = chooser.getSelectedFile().getPath();
            field_Anhang.setText(Filename);
        }
    }    // GEN-LAST:event_AnhangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /*
         *  If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        /**
         *       try {
         *           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         *               if ("Nimbus".equals(info.getName())) {
         *                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
         *                   break;
         *               }
         *           }
         *       } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
         *           java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         *       }
         */

        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(
            () -> {
                _DlgMail dialog = new _DlgMail(new javax.swing.JFrame(), true);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                             @Override
                                             public void windowClosing(java.awt.event.WindowEvent e) {
                                                 dialog.dispose();
                                             }
                                         });
                dialog.setVisible(true);
            });
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
