/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen f¸r die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import com.toedter.calendar.*;
import net.miginfocom.swing.*;

/**
 *
 * @author Thomas Zimmermann
 */
public class _DlgUebersichtUmsaetze extends javax.swing.JDialog {

    /**
     * Creates new form _DlgUebersichtUmsaetze
     *
     * @param parent
     * @param modal
     */
    public _DlgUebersichtUmsaetze(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //buttonGroupAusgabeformat.add(jRadioButtonPDF);
        //buttonGroupAusgabeformat.add(jRadioButtonXLS);
        //buttonGroupAusgabeformat.add(jRadioButtonDoc);
        //buttonGroupRechnungen.add(rbAlle);
        //buttonGroupRechnungen.add(rbBezahlt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        label2 = new JLabel();
        jLabelZeitraum = new JLabel();
        jLabelAusgabeformat = new JLabel();
        jLabelVon = new JLabel();
        jLabelBis = new JLabel();
        jRadioButtonPDF = new JRadioButton();
        jDateChooserVon = new JDateChooser();
        jDateChooserBis = new JDateChooser();
        jRadioButtonXLS = new JRadioButton();
        jRadioButtonDoc = new JRadioButton();
        label1 = new JLabel();
        rbAlle = new JRadioButton();
        rbBezahlt = new JRadioButton();
        jButtonDrucken = new JButton();
        jButtonSchlieﬂen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles Verlag");
        setResizable(false);
        setFont(new Font(Font.DIALOG, Font.BOLD, 12));
        setMinimumSize(new Dimension(415, 350));
        var contentPane = getContentPane();
        contentPane.setLayout(null);

        //======== panel1 ========
        {
            panel1.setLayout(null);

            //---- label2 ----
            label2.setText("\u00dcbersicht der Ums\u00e4tze");
            label2.setFont(label2.getFont().deriveFont(label2.getFont().getStyle() | Font.BOLD));
            panel1.add(label2);
            label2.setBounds(0, 0, 381, label2.getPreferredSize().height);

            //---- jLabelZeitraum ----
            jLabelZeitraum.setFont(new Font("Tahoma", Font.BOLD, 11));
            jLabelZeitraum.setText("Zeitraum");
            panel1.add(jLabelZeitraum);
            jLabelZeitraum.setBounds(0, 48, 87, jLabelZeitraum.getPreferredSize().height);

            //---- jLabelAusgabeformat ----
            jLabelAusgabeformat.setFont(new Font("Tahoma", Font.BOLD, 11));
            jLabelAusgabeformat.setText("Ausgabeformat");
            panel1.add(jLabelAusgabeformat);
            jLabelAusgabeformat.setBounds(new Rectangle(new Point(293, 48), jLabelAusgabeformat.getPreferredSize()));

            //---- jLabelVon ----
            jLabelVon.setText("von ...");
            panel1.add(jLabelVon);
            jLabelVon.setBounds(0, 73, 87, jLabelVon.getPreferredSize().height);

            //---- jLabelBis ----
            jLabelBis.setText("... bis");
            panel1.add(jLabelBis);
            jLabelBis.setBounds(94, 73, 87, jLabelBis.getPreferredSize().height);

            //---- jRadioButtonPDF ----
            jRadioButtonPDF.setSelected(true);
            jRadioButtonPDF.setText("PDF");
            panel1.add(jRadioButtonPDF);
            jRadioButtonPDF.setBounds(293, 69, 88, jRadioButtonPDF.getPreferredSize().height);
            panel1.add(jDateChooserVon);
            jDateChooserVon.setBounds(0, 101, 115, jDateChooserVon.getPreferredSize().height);
            panel1.add(jDateChooserBis);
            jDateChooserBis.setBounds(120, 101, 116, jDateChooserBis.getPreferredSize().height);

            //---- jRadioButtonXLS ----
            jRadioButtonXLS.setText("XLS");
            panel1.add(jRadioButtonXLS);
            jRadioButtonXLS.setBounds(293, 99, 88, jRadioButtonXLS.getPreferredSize().height);

            //---- jRadioButtonDoc ----
            jRadioButtonDoc.setText("DOC");
            panel1.add(jRadioButtonDoc);
            jRadioButtonDoc.setBounds(293, 129, 88, jRadioButtonDoc.getPreferredSize().height);

            //---- label1 ----
            label1.setText("Umfang");
            label1.setFont(label1.getFont().deriveFont(label1.getFont().getStyle() | Font.BOLD));
            panel1.add(label1);
            label1.setBounds(0, 159, 87, label1.getPreferredSize().height);

            //---- rbAlle ----
            rbAlle.setText("f\u00fcr Umsatzsteuervoranmeldung => alle Rechnungen");
            panel1.add(rbAlle);
            rbAlle.setBounds(0, 180, 381, rbAlle.getPreferredSize().height);

            //---- rbBezahlt ----
            rbBezahlt.setSelected(true);
            rbBezahlt.setText("f\u00fcr Umsatzsteuererkl\u00e4rung => nur bezahlte Rechnungen");
            panel1.add(rbBezahlt);
            rbBezahlt.setBounds(0, 210, 381, rbBezahlt.getPreferredSize().height);

            //---- jButtonDrucken ----
            jButtonDrucken.setText("Drucken");
            jButtonDrucken.addActionListener(e -> jButtonDruckenActionPerformed(e));
            panel1.add(jButtonDrucken);
            jButtonDrucken.setBounds(125, 260, 121, jButtonDrucken.getPreferredSize().height);

            //---- jButtonSchlieﬂen ----
            jButtonSchlieﬂen.setText("Schlie\u00dfen");
            jButtonSchlieﬂen.addActionListener(e -> jButtonSchlieﬂenActionPerformed(e));
            panel1.add(jButtonSchlieﬂen);
            jButtonSchlieﬂen.setBounds(250, 260, 119, jButtonSchlieﬂen.getPreferredSize().height);

            { // compute preferred size
                Dimension preferredSize = new Dimension();
                for(int i = 0; i < panel1.getComponentCount(); i++) {
                    Rectangle bounds = panel1.getComponent(i).getBounds();
                    preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                    preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
                }
                Insets insets = panel1.getInsets();
                preferredSize.width += insets.right;
                preferredSize.height += insets.bottom;
                panel1.setMinimumSize(preferredSize);
                panel1.setPreferredSize(preferredSize);
            }
        }
        contentPane.add(panel1);
        panel1.setBounds(new Rectangle(new Point(10, 11), panel1.getPreferredSize()));

        { // compute preferred size
            Dimension preferredSize = new Dimension();
            for(int i = 0; i < contentPane.getComponentCount(); i++) {
                Rectangle bounds = contentPane.getComponent(i).getBounds();
                preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
            }
            Insets insets = contentPane.getInsets();
            preferredSize.width += insets.right;
            preferredSize.height += insets.bottom;
            contentPane.setMinimumSize(preferredSize);
            contentPane.setPreferredSize(preferredSize);
        }
        pack();
        setLocationRelativeTo(getOwner());

        //---- buttonGroupAusgabeformat ----
        var buttonGroupAusgabeformat = new ButtonGroup();
        buttonGroupAusgabeformat.add(jRadioButtonPDF);
        buttonGroupAusgabeformat.add(jRadioButtonXLS);
        buttonGroupAusgabeformat.add(jRadioButtonDoc);

        //---- buttonGroupRechnungen ----
        var buttonGroupRechnungen = new ButtonGroup();
        buttonGroupRechnungen.add(rbAlle);
        buttonGroupRechnungen.add(rbBezahlt);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSchlieﬂenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSchlieﬂenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSchlieﬂenActionPerformed

    private void jButtonDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDruckenActionPerformed
        // TODO add your handling code here:
        java.util.Date vonDate = jDateChooserVon.getDate();
        java.util.Date bisDate = jDateChooserBis.getDate();

        if (jRadioButtonPDF.isSelected()) { // Format PDF
            berUmsatz.berUmsatzPDF(rbAlle.isSelected(), Modulhelferlein.printDateFormat("yyyy-MM-dd", vonDate), Modulhelferlein.printDateFormat("yyyy-MM-dd", bisDate));
        } else if (jRadioButtonXLS.isSelected()) { // Format XLSX
            berUmsatz.berUmsatzXLS(rbAlle.isSelected(), Modulhelferlein.printDateFormat("yyyy-MM-dd", vonDate), Modulhelferlein.printDateFormat("yyyy-MM-dd", bisDate));
        } else { // Format DOCX
            berUmsatz.berUmsatzDOC(rbAlle.isSelected(), Modulhelferlein.printDateFormat("yyyy-MM-dd", vonDate), Modulhelferlein.printDateFormat("yyyy-MM-dd", bisDate));
        }
        this.dispose();
    }//GEN-LAST:event_jButtonDruckenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /**
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
         * } catch (ClassNotFoundException | InstantiationException |
         * IllegalAccessException | javax.swing.UnsupportedLookAndFeelException
         * ex) {
         * java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); }
         */
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgUebersichtUmsaetze dialog = new _DlgUebersichtUmsaetze(new javax.swing.JFrame(), true);

            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel label2;
    private JLabel jLabelZeitraum;
    private JLabel jLabelAusgabeformat;
    private JLabel jLabelVon;
    private JLabel jLabelBis;
    private JRadioButton jRadioButtonPDF;
    private JDateChooser jDateChooserVon;
    private JDateChooser jDateChooserBis;
    private JRadioButton jRadioButtonXLS;
    private JRadioButton jRadioButtonDoc;
    private JLabel label1;
    private JRadioButton rbAlle;
    private JRadioButton rbBezahlt;
    private JButton jButtonDrucken;
    private JButton jButtonSchlieﬂen;
    // End of variables declaration//GEN-END:variables

    //private ButtonGroup buttonGroupRechnungen;
    //private ButtonGroup buttonGroupAusgabeformat;
}
