/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author Thomas Zimmermann
 */
public class _DlgAusgabeAdressen extends javax.swing.JDialog {

    /**
     * Creates new form _DlgAusgabeAdressen
     *
     * @param parent
     * @param modal
     */
    public _DlgAusgabeAdressen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroupAdressArt.add(jRadioButtonArtAlle);
        buttonGroupAdressArt.add(jRadioButtonArtAuswahl);
        buttonGroupAusgabeFormat.add(jRadioButtonDOC);
        buttonGroupAusgabeFormat.add(jRadioButtonPDF);
        buttonGroupAusgabeFormat.add(jRadioButtonXLS);
        for (String AdressTypListe : Modulhelferlein.AdressTypListe) {
            jComboBoxAdressArt.addItem(AdressTypListe);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jRadioButtonArtAlle = new JRadioButton();
        jRadioButtonArtAuswahl = new JRadioButton();
        jComboBoxAdressArt = new JComboBox<>();
        jRadioButtonPDF = new JRadioButton();
        jRadioButtonXLS = new JRadioButton();
        jRadioButtonDOC = new JRadioButton();
        jLabel4 = new JLabel();
        jButtonDrucken = new JButton();
        jButtonSchliessen = new JButton();
        jRadioButtonArtEtikett = new JRadioButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carol Hartmann Miles Verlag");
        setResizable(false);
        Container contentPane = getContentPane();

        //======== panel1 ========
        {

            //---- jLabel2 ----
            jLabel2.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel2.setText("Ausgabe der Adressen");
            jLabel2.setRequestFocusEnabled(false);

            //---- jLabel3 ----
            jLabel3.setText("Adressart");

            //---- jRadioButtonArtAlle ----
            jRadioButtonArtAlle.setText("Alle Adressen");
            jRadioButtonArtAlle.setToolTipText("Ausgabe alles Adressen");

            //---- jRadioButtonArtAuswahl ----
            jRadioButtonArtAuswahl.setText("bestimmte");
            jRadioButtonArtAuswahl.setToolTipText("Ausgabe des ausgew\u00e4hlten Adresstyps");

            //---- jComboBoxAdressArt ----
            jComboBoxAdressArt.setToolTipText("Auswahlliste f\u00fcr die auszugebenden Adress-Typen");

            //---- jRadioButtonPDF ----
            jRadioButtonPDF.setSelected(true);
            jRadioButtonPDF.setText("PDF");
            jRadioButtonPDF.setToolTipText("Ausgabe als ODF-Dokument");

            //---- jRadioButtonXLS ----
            jRadioButtonXLS.setText("XLS");
            jRadioButtonXLS.setToolTipText("Ausgabe als Excel-Dokument");

            //---- jRadioButtonDOC ----
            jRadioButtonDOC.setText("DOC");
            jRadioButtonDOC.setToolTipText("Ausgabe als Word-Dokument");

            //---- jLabel4 ----
            jLabel4.setText("Ausgabeformat");

            //---- jButtonDrucken ----
            jButtonDrucken.setText("Drucken");
            jButtonDrucken.setToolTipText("Ausgabe der ausgew\u00e4hlten Adressen");
            jButtonDrucken.addActionListener(e -> jButtonDruckenActionPerformed(e));

            //---- jButtonSchliessen ----
            jButtonSchliessen.setText("Schlie\u00dfen");
            jButtonSchliessen.setToolTipText("Schlie\u00dfen des Dialoges");
            jButtonSchliessen.addActionListener(e -> jButtonSchliessenActionPerformed(e));

            //---- jRadioButtonArtEtikett ----
            jRadioButtonArtEtikett.setSelected(true);
            jRadioButtonArtEtikett.setText("aktuelles Etikett");

            GroupLayout panel1Layout = new GroupLayout(panel1);
            panel1.setLayout(panel1Layout);
            panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jLabel2)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(241, 241, 241)
                                .addComponent(jLabel4))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonArtAlle)
                                .addGap(197, 197, 197)
                                .addComponent(jRadioButtonPDF))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonArtAuswahl)
                                .addGap(213, 213, 213)
                                .addComponent(jRadioButtonXLS))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jComboBoxAdressArt, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jRadioButtonDOC))
                            .addComponent(jRadioButtonArtEtikett)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jButtonDrucken)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSchliessen)))
                        .addContainerGap(26, Short.MAX_VALUE))
            );
            panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButtonArtAlle)
                            .addComponent(jRadioButtonPDF))
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jRadioButtonArtAuswahl)
                            .addComponent(jRadioButtonXLS))
                        .addGap(1, 1, 1)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jComboBoxAdressArt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonDOC))
                        .addGap(47, 47, 47)
                        .addComponent(jRadioButtonArtEtikett)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup()
                            .addComponent(jButtonDrucken)
                            .addComponent(jButtonSchliessen))
                        .addContainerGap())
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSchliessenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSchliessenActionPerformed

    private void jButtonDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDruckenActionPerformed
        // TODO add your handling code here:
        berAdresse fenster = new berAdresse();
        if (jRadioButtonArtAlle.isSelected()) { // Ausgabe aller Adressen
            if (jRadioButtonPDF.isSelected()) { // Format PDF
                fenster.berichtPDF("ALLE");
            } else if (jRadioButtonXLS.isSelected()) { // Format XLSX
                fenster.berichtXLSX("ALLE");
            } else { // Format DOCX
                fenster.berichtDOCX("ALLE");
            }
        } else if (jRadioButtonArtEtikett.isSelected()) {
            _DlgAdresseDrucken.main(argumente);
        } else { // Ausgabe der ausgewählten Adresstypen
            if (jRadioButtonPDF.isSelected()) { // Format PDF
                fenster.berichtPDF((String) jComboBoxAdressArt.getSelectedItem());
            } else if (jRadioButtonXLS.isSelected()) { // Format XLSX
                fenster.berichtXLSX((String) jComboBoxAdressArt.getSelectedItem());
            } else { // Format DOCX
                fenster.berichtDOCX((String) jComboBoxAdressArt.getSelectedItem());
            }
        }
        // Dialog schließen
        this.dispose();
    }//GEN-LAST:event_jButtonDruckenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /**
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
         * } catch (ClassNotFoundException | InstantiationException |
         * IllegalAccessException | javax.swing.UnsupportedLookAndFeelException
         * ex) {
         * java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); }
         */
        //</editor-fold>
        if (args != null) {
            argumente[0] = args[0];
            argumente[1] = args[1];
            argumente[2] = args[2];
            argumente[3] = args[3];
            argumente[4] = args[4];
            argumente[5] = args[5];
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgAusgabeAdressen dialog = new _DlgAusgabeAdressen(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JRadioButton jRadioButtonArtAlle;
    private JRadioButton jRadioButtonArtAuswahl;
    private JComboBox<String> jComboBoxAdressArt;
    private JRadioButton jRadioButtonPDF;
    private JRadioButton jRadioButtonXLS;
    private JRadioButton jRadioButtonDOC;
    private JLabel jLabel4;
    private JButton jButtonDrucken;
    private JButton jButtonSchliessen;
    private JRadioButton jRadioButtonArtEtikett;
    // End of variables declaration//GEN-END:variables

    private static String[] argumente = {"-","-","-","-","-","-"};
    private ButtonGroup buttonGroupAdressArt = new ButtonGroup();
    private ButtonGroup buttonGroupAusgabeFormat = new ButtonGroup();
}

        