/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JFileChooser;
import javax.swing.LayoutStyle;
import com.toedter.calendar.*;
import net.miginfocom.swing.*;

/**
 *
 * @author Thomas Zimmermann
 */
public class _DlgVerkaufsstatistikCHMVGesamt extends javax.swing.JDialog {

    /**
     * Creates new form _DlgVerkaufsstatistikCHMV
     *
     * @param parent
     * @param modal
     */
    public _DlgVerkaufsstatistikCHMVGesamt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Ausgabeformat.add(PDF);
        Ausgabeformat.add(XLS);
        Ausgabeformat.add(DOC);
        Umfang.add(rbMiles);
        Umfang.add(rbBOD);
        Umfang.add(rbGesamt);
        Sortierung.add(rbAutor);
        Sortierung.add(rbTitel);
        Sortierung.add(rbISBN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        field_von = new JDateChooser();
        field_bis = new JDateChooser();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        PDF = new JRadioButton();
        rbAutor = new JRadioButton();
        XLS = new JRadioButton();
        rbTitel = new JRadioButton();
        jLabel5 = new JLabel();
        DOC = new JRadioButton();
        rbISBN = new JRadioButton();
        rbMiles = new JRadioButton();
        rbBOD = new JRadioButton();
        btnSalesBOD = new JButton();
        lblSalesCSV = new JTextField();
        rbGesamt = new JRadioButton();
        Drucken = new JButton();
        Schliessen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles Verlag");
        setResizable(false);
        setMinimumSize(new Dimension(475, 370));
        setFont(new Font(Font.DIALOG, Font.BOLD, 12));
        var contentPane = getContentPane();
        contentPane.setLayout(null);

        //======== panel1 ========
        {
            panel1.setLayout(null);

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel1.setText("Verkaufsstatistik ");
            panel1.add(jLabel1);
            jLabel1.setBounds(0, 0, 118, jLabel1.getPreferredSize().height);

            //---- jLabel3 ----
            jLabel3.setText("von");
            panel1.add(jLabel3);
            jLabel3.setBounds(0, 45, 95, jLabel3.getPreferredSize().height);

            //---- jLabel4 ----
            jLabel4.setText("bis");
            panel1.add(jLabel4);
            jLabel4.setBounds(123, 45, 87, jLabel4.getPreferredSize().height);
            panel1.add(field_von);
            field_von.setBounds(0, 64, 118, 23);
            panel1.add(field_bis);
            field_bis.setBounds(123, 64, 118, 23);

            //---- jLabel6 ----
            jLabel6.setText("Ausgabeformat");
            jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | Font.BOLD));
            panel1.add(jLabel6);
            jLabel6.setBounds(new Rectangle(new Point(255, 45), jLabel6.getPreferredSize()));

            //---- jLabel7 ----
            jLabel7.setText("Sortierung");
            jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | Font.BOLD));
            panel1.add(jLabel7);
            jLabel7.setBounds(358, 45, 85, jLabel7.getPreferredSize().height);

            //---- PDF ----
            PDF.setText("PDF");
            PDF.setEnabled(false);
            panel1.add(PDF);
            PDF.setBounds(255, 65, 88, PDF.getPreferredSize().height);

            //---- rbAutor ----
            rbAutor.setSelected(true);
            rbAutor.setText("Autor");
            panel1.add(rbAutor);
            rbAutor.setBounds(358, 64, 85, rbAutor.getPreferredSize().height);

            //---- XLS ----
            XLS.setText("XLS");
            XLS.setSelected(true);
            panel1.add(XLS);
            XLS.setBounds(255, 95, 88, XLS.getPreferredSize().height);

            //---- rbTitel ----
            rbTitel.setText("Titel");
            panel1.add(rbTitel);
            rbTitel.setBounds(358, 92, 85, rbTitel.getPreferredSize().height);

            //---- jLabel5 ----
            jLabel5.setText("Umfang");
            jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | Font.BOLD));
            panel1.add(jLabel5);
            jLabel5.setBounds(0, 120, 68, 23);

            //---- DOC ----
            DOC.setText("DOC");
            DOC.setEnabled(false);
            panel1.add(DOC);
            DOC.setBounds(255, 120, 88, DOC.getPreferredSize().height);

            //---- rbISBN ----
            rbISBN.setText("ISBN");
            panel1.add(rbISBN);
            rbISBN.setBounds(358, 120, 85, rbISBN.getPreferredSize().height);

            //---- rbMiles ----
            rbMiles.setSelected(true);
            rbMiles.setText("Direktvertrieb Miles-Verlag");
            panel1.add(rbMiles);
            rbMiles.setBounds(0, 148, 210, rbMiles.getPreferredSize().height);

            //---- rbBOD ----
            rbBOD.setText("Books on Demand-Verk\u00e4ufe");
            panel1.add(rbBOD);
            rbBOD.setBounds(0, 176, 210, rbBOD.getPreferredSize().height);

            //---- btnSalesBOD ----
            btnSalesBOD.setText("...");
            btnSalesBOD.addActionListener(e -> btnSalesBODActionPerformed(e));
            panel1.add(btnSalesBOD);
            btnSalesBOD.setBounds(new Rectangle(new Point(23, 204), btnSalesBOD.getPreferredSize()));

            //---- lblSalesCSV ----
            lblSalesCSV.setText("SALES.CSV");
            lblSalesCSV.setEnabled(false);
            lblSalesCSV.setFocusable(false);
            panel1.add(lblSalesCSV);
            lblSalesCSV.setBounds(73, 204, 357, 23);

            //---- rbGesamt ----
            rbGesamt.setText("Gesamtverk\u00e4ufe");
            panel1.add(rbGesamt);
            rbGesamt.setBounds(0, 232, 118, rbGesamt.getPreferredSize().height);

            //---- Drucken ----
            Drucken.setText("Drucken");
            Drucken.addActionListener(e -> DruckenActionPerformed(e));
            panel1.add(Drucken);
            Drucken.setBounds(240, 285, 88, Drucken.getPreferredSize().height);

            //---- Schliessen ----
            Schliessen.setText("Abbrechen");
            Schliessen.addActionListener(e -> SchliessenActionPerformed(e));
            panel1.add(Schliessen);
            Schliessen.setBounds(new Rectangle(new Point(350, 285), Schliessen.getPreferredSize()));

            { // compute preferred size
                Dimension preferredSize = new Dimension();
                for(int i = 0; i < panel1.getComponentCount(); i++) {
                    Rectangle bounds = panel1.getComponent(i).getBounds();
                    preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                    preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
                }
                Insets insets = panel1.getInsets();
                preferredSize.width += insets.right;
                preferredSize.height += insets.bottom;
                panel1.setMinimumSize(preferredSize);
                panel1.setPreferredSize(preferredSize);
            }
        }
        contentPane.add(panel1);
        panel1.setBounds(new Rectangle(new Point(10, 11), panel1.getPreferredSize()));

        { // compute preferred size
            Dimension preferredSize = new Dimension();
            for(int i = 0; i < contentPane.getComponentCount(); i++) {
                Rectangle bounds = contentPane.getComponent(i).getBounds();
                preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
            }
            Insets insets = contentPane.getInsets();
            preferredSize.width += insets.right;
            preferredSize.height += insets.bottom;
            contentPane.setMinimumSize(preferredSize);
            contentPane.setPreferredSize(preferredSize);
        }
        setSize(465, 360);
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void DruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DruckenActionPerformed
        // TODO add your handling code here:
        java.util.Date vonDate = null;
        vonDate = field_von.getDate();
        java.util.Date bisDate = null;
        bisDate = field_bis.getDate();
        String strVon = "1970-01-01";
        String strBis = "1970-01-01";
        if (vonDate != null) {
            strVon = ModulHelferlein.printDateFormat("yyyy-MM-dd", vonDate);
        }
        if (bisDate != null) {
            strBis = ModulHelferlein.printDateFormat("yyyy-MM-dd", bisDate);
        }

        if (rbMiles.isSelected()) {
            if (rbAutor.isSelected()) {
                if (PDF.isSelected()) {               // Format PDF
                    berVerkaufMiles.bericht("Autor", "PDF", strVon, strBis);
                    //berVerkaufMilesAutor.berichtPDF(strVon, strBis);
                } else if (XLS.isSelected()) {        // Format XLSX
                    berVerkaufMiles.bericht("Autor", "XLS", strVon, strBis);
                    // berVerkaufMilesAutor.berichtXLS(strVon, strBis);
                } else {                              // Format DOCX
                    berVerkaufMiles.bericht("Autor", "DOC", strVon, strBis);
                    // berVerkaufMilesAutor.berichtDOC(strVon, strBis);
                }                                     // if
            } else if (rbISBN.isSelected()) {                                  // buch is selected
                if (PDF.isSelected()) {               // Format PDF
                    berVerkaufMiles.bericht("ISBN", "PDF", strVon, strBis);
                    // berVerkaufMilesBuch.berichtPDF(strVon, strBis);
                } else if (XLS.isSelected()) {        // Format XLSX
                    berVerkaufMiles.bericht("ISBN", "XLS", strVon, strBis);
                    // berVerkaufMilesBuch.berichtXLS(strVon, strBis);
                } else {                              // Format DOCX
                    berVerkaufMiles.bericht("ISBN", "DOC", strVon, strBis);
                    // berVerkaufMilesBuch.berichtDOC(strVon, strBis);
                }                                     // if Format
            } else {
                if (PDF.isSelected()) {               // Format PDF
                    berVerkaufMiles.bericht("Titel", "PDF", strVon, strBis);
                } else if (XLS.isSelected()) {        // Format XLSX
                    berVerkaufMiles.bericht("Titel", "XLS", strVon, strBis);
                } else {                              // Format DOCX
                    berVerkaufMiles.bericht("Titel", "DOC", strVon, strBis);
                }                                     // if Format
            } // if sortierung
        } else if (rbBOD.isSelected()) {
            if (sFilePathAndName.length() == 0) {
                ModulHelferlein.Fehlermeldung("Sie haben keine Datei ausgewählt!");
            } else {
                if (rbAutor.isSelected()) {
                    if (PDF.isSelected()) {           // Format PDF
                        berVerkaufBOD.bericht(sFilePathAndName, "Autor", "PDF", strVon, strBis);
                    } else if (XLS.isSelected()) {    // Format XLSX
                        berVerkaufBOD.bericht(sFilePathAndName, "Autor", "XLS", strVon, strBis);
                    } else {                          // Format DOCX
                        berVerkaufBOD.bericht(sFilePathAndName, "Autor", "DOC", strVon, strBis);
                    }                                 // if Format
                } else if (rbISBN.isSelected()) {                              // buch is selected
                    if (PDF.isSelected()) {           // Format PDF
                        berVerkaufBOD.bericht(sFilePathAndName, "ISBN", "PDF", strVon, strBis);
                    } else if (XLS.isSelected()) {    // Format XLSX
                        berVerkaufBOD.bericht(sFilePathAndName, "ISBN", "XLS", strVon, strBis);
                    } else {                          // Format DOCX
                        berVerkaufBOD.bericht(sFilePathAndName, "ISBN", "DOC", strVon, strBis);
                    }                                 // if Format
                } else {
                    if (PDF.isSelected()) {           // Format PDF
                        berVerkaufBOD.bericht(sFilePathAndName, "Titel", "PDF", strVon, strBis);
                    } else if (XLS.isSelected()) {    // Format XLSX
                        berVerkaufBOD.bericht(sFilePathAndName, "Titel", "XLS", strVon, strBis);
                    } else {                          // Format DOCX
                        berVerkaufBOD.bericht(sFilePathAndName, "Titel", "DOC", strVon, strBis);
                    }                                 // if Format
                }// if Sortierung
            }
        } else if (rbGesamt.isSelected()) {   // berVerkaufGesamt
            if (sFilePathAndName.length() == 0) {
                ModulHelferlein.Fehlermeldung("Sie haben keine Datei ausgewählt!");
            } else {
                if (rbAutor.isSelected()) {
                    if (PDF.isSelected()) {           // Format PDF
                        berVerkaufGesamt.bericht(sFilePathAndName, "Autor", "PDF", strVon, strBis);
                    } else if (XLS.isSelected()) {    // Format XLSX
                        berVerkaufGesamt.bericht(sFilePathAndName, "Autor", "XLS", strVon, strBis);
                    } else {                          // Format DOCX
                        berVerkaufGesamt.bericht(sFilePathAndName, "Autor", "DOC", strVon, strBis);
                    }                                 // if Format
                } else if (rbISBN.isSelected()) {                              // buch is selected
                    if (PDF.isSelected()) {           // Format PDF
                        berVerkaufGesamt.bericht(sFilePathAndName, "ISBN", "PDF", strVon, strBis);
                    } else if (XLS.isSelected()) {    // Format XLSX
                        berVerkaufGesamt.bericht(sFilePathAndName, "ISBN", "XLS", strVon, strBis);
                    } else {                          // Format DOCX
                        berVerkaufGesamt.bericht(sFilePathAndName, "ISBN", "DOC", strVon, strBis);
                    }                                 // if Format
                } else {
                    if (PDF.isSelected()) {           // Format PDF
                        berVerkaufGesamt.bericht(sFilePathAndName, "Titel", "PDF", strVon, strBis);
                    } else if (XLS.isSelected()) {    // Format XLSX
                        berVerkaufGesamt.bericht(sFilePathAndName, "Titel", "XLS", strVon, strBis);
                    } else {                          // Format DOCX
                        berVerkaufGesamt.bericht(sFilePathAndName, "Titel", "DOC", strVon, strBis);
                    }                                 // if Format
                }
            }
        }                                             // if Umfang
        this.dispose();
    }//GEN-LAST:event_DruckenActionPerformed

    private void SchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchliessenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SchliessenActionPerformed

    private void btnSalesBODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesBODActionPerformed
        // TODO add your handling code here:
        chooser.setFileFilter(new ModulMyFilter(".csv"));
        chooser.setAcceptAllFileFilterUsed(false);

        int Ergebnis = chooser.showDialog(null, "SALES.CSV - Datei von BoD wählen");

        if (Ergebnis == JFileChooser.APPROVE_OPTION) {
            try {
                sFilePathAndName = chooser.getSelectedFile().getCanonicalPath();
                lblSalesCSV.setText(sFilePathAndName);
            } catch (IOException e) {
                ModulHelferlein.Fehlermeldung("IO-Exception: " + e.getMessage());
            }    // try
        }        // if
    }//GEN-LAST:event_btnSalesBODActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /**
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
         * } catch (ClassNotFoundException | InstantiationException |
         * IllegalAccessException | javax.swing.UnsupportedLookAndFeelException
         * ex) {
         * java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); }
         */
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            _DlgVerkaufsstatistikCHMVGesamt dialog = new _DlgVerkaufsstatistikCHMVGesamt(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.dispose();
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JDateChooser field_von;
    private JDateChooser field_bis;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JRadioButton PDF;
    private JRadioButton rbAutor;
    private JRadioButton XLS;
    private JRadioButton rbTitel;
    private JLabel jLabel5;
    private JRadioButton DOC;
    private JRadioButton rbISBN;
    private JRadioButton rbMiles;
    private JRadioButton rbBOD;
    private JButton btnSalesBOD;
    private JTextField lblSalesCSV;
    private JRadioButton rbGesamt;
    private JButton Drucken;
    private JButton Schliessen;
    // End of variables declaration//GEN-END:variables

    JFileChooser chooser = new JFileChooser(new File(System.getProperty("user.dir")));
    String sFilePathAndName = "";

    private ButtonGroup Ausgabeformat = new ButtonGroup();
    private ButtonGroup Umfang = new ButtonGroup();
    private ButtonGroup Sortierung = new ButtonGroup();
}
