/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen für die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von Software
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Store;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

/**
 *
 * @author Thomas Zimmermann
 */
public class ModulEMail {

    /**
     * Creates new form _DlgMail
     *
     * @param parent
     * @param modal
     */
    public ModulEMail(java.awt.Frame parent, boolean modal) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private static void MailSenden() {

        // TODO add your handling code here:
        System.out.println("TLS Email Start");

        // change accordingly 
        String host = ModulHelferlein.MailHost;
        System.out.println("- host     " + host);

        String port = ModulHelferlein.MailPort;
        System.out.println("- port     " + port);

        String IMAPhost = ModulHelferlein.MailIMAPHost;
        System.out.println("- host     " + IMAPhost);

        String IMAPport = ModulHelferlein.MailIMAPPort;
        System.out.println("- port     " + IMAPport);

        String username = ModulHelferlein.MailUser;
        System.out.println("- username " + username);

        String password = ModulHelferlein.MailPass;
        System.out.println("- password " + password);

        String from = username;
        System.out.println("- from     " + username);

        String to = Empfaenger;
        System.out.println("- to       " + to);

        String record = ModulHelferlein.MailIMAPGesendet;   //"Sent Items"

        // Get the session object 
        // Get system properties 
        Properties properties = System.getProperties();

        // Setup mail server 
        properties.setProperty("mail.smtp.host", host);
        properties.setProperty("mail.imap.host", IMAPhost);

        // SSL Port 
        properties.put("mail.smtp.port", port);
        properties.put("mail.imap.port", IMAPport);

        // enable authentication 
        properties.put("mail.smtp.auth", "true");
        //properties.put("mail.imap.auth", "true");

        // SSL Factory 
        properties.put("mail.smtp.socketFactory.class",
                "javax.net.ssl.SSLSocketFactory");

        properties.put("mail.imap.starttls.enable", "true");

        properties.put("mail.transport.protocol", "smtp");
        //properties.put("mail.store.protocol", "imap");

        // creating Session instance referenced to  
        // Authenticator object to pass in  
        // Session.getInstance argument 
        Session session = Session.getDefaultInstance(properties,
                new javax.mail.Authenticator() {

            // override the getPasswordAuthentication  
            // method 
            protected PasswordAuthentication
                    getPasswordAuthentication() {
                return new PasswordAuthentication(username,
                        password);
            }
        });

        //compose the message 
        try {
            // javax.mail.internet.MimeMessage class is mostly  
            // used for abstraction. 
            MimeMessage message = new MimeMessage(session);

            // header field of the header. 
            message.setFrom(new InternetAddress(username));

            //InternetAddress[] addresses = new InternetAddress[2];
            //addresses[0] = new InternetAddress(to);
            //addresses[1] = new InternetAddress(from);            
            //message.setRecipients(Message.RecipientType.TO, addresses);
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.addRecipient(Message.RecipientType.CC, new InternetAddress(username));

            // Set Subject: header field
            message.setSubject("Ihre Bestellung vom " + Datum);

            // Create a multipar message
            Multipart multipart = new MimeMultipart();

            // Create the message part
            BodyPart messageBodyPart = new MimeBodyPart();

            // Fill the message
            String text = "Herzlichen Dank für Ihre Bestellung. \n";

            if (DHL.equals("")) {
                text = text + "Wir haben diese heute per Post/DHL versendet.\n";
            } else {
                text = text + "Wir haben diese heute per Post/DHL versendet. Die Sendungsnummer lautet " + DHL + "\n";
            }
            text = text + "\n"
                    + "Die Rechnung haben wir als Anhang beigefügt."
                    + "\n"
                    + "\n"
                    + "Mit freundlichen Grüßen\n"
                    + ModulHelferlein.CHMVBenutzer + "\n"
                    + "\n"
                    + "Carola Hartmann Miles Verlag\n"
                    + "George-Caylay-Straße 38\n"
                    + "14089 Berlin\n"
                    + "Telefon +49 (30) 36877788";

            // Set text message part
            messageBodyPart.setText(text);
            multipart.addBodyPart(messageBodyPart);

            // Part two is attachment
            if (Filename.length() > 0) {
                messageBodyPart = new MimeBodyPart();

                DataSource source = new FileDataSource(Filename);

                messageBodyPart.setDataHandler(new DataHandler(source));
                messageBodyPart.setFileName(Filename);
                multipart.addBodyPart(messageBodyPart);
            }

            // Send the complete message parts
            message.setContent(multipart);

            //message.setSubject("Ihre Bestellung vom " + Datum);
            //message.setText("Hello, aas is sending email ");
            // Send message 
            Transport.send(message);
            ModulHelferlein.Infomeldung("Mail wurde gesendet");
            System.out.println("Mail wurde gesendet.");

            // Message im Ordner gesendet - sent ablegen
            /*
	     * Save a copy of the message
             */
            // get a store object
            Store store = session.getStore("imaps");
            store.connect(IMAPhost, username, password);

            Folder folder = store.getFolder(record);
            if (folder == null) {
                System.err.println("Finde den gesendet-Ordner nicht.");
                ModulHelferlein.Fehlermeldung("Finde den gesendet-Ordner nicht!");
                //System.exit(1);
            } else {
                Message[] msgs = new Message[1];
                msgs[0] = message;
                folder.appendMessages(msgs);

                ModulHelferlein.Infomeldung("Mail wurde im Ordner '" + ModulHelferlein.MailIMAPGesendet + "' gespeichert");
                System.out.println("Mail was recorded successfully.");
            }

        } catch (MessagingException mex) {
            ModulHelferlein.Fehlermeldung("E-Mail-versenden", mex.getMessage());
        }
    }

// GEN-LAST:event_SendenActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Filename
                = args[0];
        KundeID
                = args[1];
        DHL
                = args[3];
        Datum
                = args[4];

        if (KundeID
                .equals("-1")) {
            Empfaenger
                    = args[2];

        } else {

        }
        MailSenden();

    }

    private static String Filename
            = "";
    private static String KundeID
            = "";
    private static String Empfaenger
            = "";
    private static String DHL
            = "";
    private static String Datum
            = "";
}


//~ Formatted by Jindent --- http://www.jindent.com
