/*
 *
 * Das JAVA-Programm Miles-Verlag Verlagsverwaltung stellt alle notwendigen
 * Funktionen f¸r die Verwaltung des Carola Hartman Miles-Verlags bereit.
 *
 * Copyright (C) 2017 EDV-Beratung und Betrieb, Entwicklung von SOftware
 *                    Dipl.Inform Thomas Zimmermann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package milesVerlagMain;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import net.miginfocom.swing.*;

/**
 *
 * @author Thomas Zimmermann
 */
public class VerwaltenDatenbankBestellnummer extends javax.swing.JDialog {

    private boolean resultIsEmpty = true;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel panel1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JTextField jTextFieldBestellnummer;
    private JButton jButtonUpdate;
    private JButton jButtonSchlieﬂen;
    // End of variables declaration//GEN-END:variables
    private Connection conn;
    private Statement SQLAnfrage;
    private ResultSet result;

    /**
     * Creates new form VerwaltenDatenbankBestellnummer
     *
     * @param parent
     * @param modal
     */
    public VerwaltenDatenbankBestellnummer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conn = null;

        // Datenbank-Treiber laden
        try {
            Class.forName(ModulHelferlein.dbDriver);
        } catch (ClassNotFoundException exept) {
            ModulHelferlein.Fehlermeldung("Treiber nicht gefunden.");
        }

        // Verbindung zur Datenbank ¸ber die JDBC-Br¸cke
        try {
            conn = DriverManager.getConnection(ModulHelferlein.dbUrl, ModulHelferlein.dbUser, ModulHelferlein.dbPassword);
        } catch (SQLException exept) {
            ModulHelferlein.Fehlermeldung("Verbindung zur Datenbank nicht moeglich.");
        }

        // final Connection conn2=conn;
        if (conn != null) {
            SQLAnfrage = null;    // Anfrage erzeugen

            try {
                SQLAnfrage = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);    // Anfrage der DB conn2 zuordnen
                result = SQLAnfrage.executeQuery("SELECT * FROM TBL_BESTELLNR");    // schickt SQL an DB und erzeugt ergebnis -> wird in result gespeichert

                // gehe zum ersten Datensatz - wenn nicht leer
                if (result.next()) {
                    resultIsEmpty = false;

                    String col_Nummer = result.getString("BESTELLNR_NUMMER");

                    jTextFieldBestellnummer.setText(col_Nummer);
                }
            } catch (SQLException exept) {
                ModulHelferlein.Fehlermeldung("BESTELLNUMMER: SQL-Exception: SQL-Anfrage nicht moeglich. "
                        + exept.getMessage());

                // System.exit(1);
            }    // try
        }        // if
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jTextFieldBestellnummer = new JTextField();
        jButtonUpdate = new JButton();
        jButtonSchlieﬂen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carola Hartmann Miles Verlag");
        setResizable(false);
        setMinimumSize(new Dimension(205, 175));
        Container contentPane = getContentPane();

        //======== panel1 ========
        {
            panel1.setPreferredSize(new Dimension(205, 175));
            panel1.setLayout(null);

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Tahoma", Font.BOLD, 12));
            jLabel1.setText("Verwalten der Bestellnummer");
            panel1.add(jLabel1);
            jLabel1.setBounds(new Rectangle(new Point(0, 0), jLabel1.getPreferredSize()));

            //---- jLabel2 ----
            jLabel2.setText("Bestellnummer");
            panel1.add(jLabel2);
            jLabel2.setBounds(0, 48, 92, jLabel2.getPreferredSize().height);

            //---- jTextFieldBestellnummer ----
            jTextFieldBestellnummer.setText(" ");
            jTextFieldBestellnummer.setToolTipText("Neue Bestellnummer");
            jTextFieldBestellnummer.addActionListener(e -> jTextFieldBestellnummerActionPerformed(e));
            panel1.add(jTextFieldBestellnummer);
            jTextFieldBestellnummer.setBounds(97, 45, 83, jTextFieldBestellnummer.getPreferredSize().height);

            //---- jButtonUpdate ----
            jButtonUpdate.setText("Update");
            jButtonUpdate.setToolTipText("Aktualisieren der Bestellnummer und schlie\u00dfen des Dialoges");
            jButtonUpdate.addActionListener(e -> jButtonUpdateActionPerformed(e));
            panel1.add(jButtonUpdate);
            jButtonUpdate.setBounds(5, 90, 100, jButtonUpdate.getPreferredSize().height);

            //---- jButtonSchlieﬂen ----
            jButtonSchlieﬂen.setText("Schlie\u00dfen");
            jButtonSchlieﬂen.setToolTipText("Schlie\u00dfen des Dialoges");
            jButtonSchlieﬂen.addActionListener(e -> jButtonSchlieﬂenActionPerformed(e));
            panel1.add(jButtonSchlieﬂen);
            jButtonSchlieﬂen.setBounds(120, 90, 95, jButtonSchlieﬂen.getPreferredSize().height);

            { // compute preferred size
                Dimension preferredSize = new Dimension();
                for(int i = 0; i < panel1.getComponentCount(); i++) {
                    Rectangle bounds = panel1.getComponent(i).getBounds();
                    preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                    preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
                }
                Insets insets = panel1.getInsets();
                preferredSize.width += insets.right;
                preferredSize.height += insets.bottom;
                panel1.setMinimumSize(preferredSize);
                panel1.setPreferredSize(preferredSize);
            }
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE))
        );
        setSize(250, 175);
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSchlieﬂenActionPerformed(java.awt.event.ActionEvent evt) {    // GEN-FIRST:event_jButtonSchlieﬂenActionPerformed

        // TODO add your handling code here:
        try {
            result.close();
            SQLAnfrage.close();
            conn.close();
        } catch (SQLException exept) {
            ModulHelferlein.Fehlermeldung("SQL-Exception: " + exept.getMessage());
        }

        this.dispose();
    }    // GEN-LAST:event_jButtonSchlieﬂenActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {    // GEN-FIRST:event_jButtonUpdateActionPerformed

        // TODO add your handling code here:
        try {
            if (ModulHelferlein.checkNumberFormatInt(jTextFieldBestellnummer.getText()) < 0) {
                ModulHelferlein.Infomeldung("fehlerhafte Eingabe - die ist keine korrekte Ganzzahl");
            } else {
                result.updateString("BESTELLNR_NUMMER", jTextFieldBestellnummer.getText());
                result.updateRow();
            }    // else
        } catch (SQLException exept) {
            ModulHelferlein.Fehlermeldung("BESTELLNUMMER: SQL-Exception: " + exept.getMessage());
        }

        // Schlieﬂen des Dialoges
        this.dispose();
    }    // GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldBestellnummerActionPerformed(java.awt.event.ActionEvent evt) {    // GEN-FIRST:event_jTextFieldBestellnummerActionPerformed

        // TODO add your handling code here:
        if (ModulHelferlein.checkNumberFormatInt(jTextFieldBestellnummer.getText()) < 0) {
            ModulHelferlein.Infomeldung("fehlerhafte Eingabe - die ist keine korrekte Ganzzahl");
        }
    }    // GEN-LAST:event_jTextFieldBestellnummerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /*
         *  If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /**
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
         * } catch (ClassNotFoundException | InstantiationException |
         * IllegalAccessException | javax.swing.UnsupportedLookAndFeelException
         * ex) {
         * java.util.logging.Logger.getLogger(CarolaHartmannMilesVerlag.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); }
         */
        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(
                () -> {
                    VerwaltenDatenbankBestellnummer dialog = new VerwaltenDatenbankBestellnummer(new javax.swing.JFrame(),
                            true);

                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            dialog.setVisible(false);
                        }
                    });
                    dialog.setVisible(true);
                });
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
